"""Write the take-home's second sample: a Kalpa warehouse nobody has queried, in its own schema.

The take-home runs the day's three rounds on data the room has not seen, so no number from the
morning can be pasted across. The sample comes from data/generate_client_zero.py, which is imported
and rerun with a different seed, so its shape, its segments and its plan line are the warehouse's
and every number in it is new. Two things are then planted for this sample alone, and only the
trainer day sheet names them:

1. A three-way Q2 revenue tie across the 19th, 20th and 21st Retail-Core positions, so a top
   twenty ships 20 rows under ROW_NUMBER, 21 under RANK and 18 under "whole ties only".
2. The generator's own falling-spend ladder, which under this seed lands on three different
   Retail-Plus members.

Usage, from the repository root:
    python3 content/W02/D3/internal/C2_W02_D03_takehome_data_INTERNAL.py
It writes content/W02/D3/data/C2_W02_D03_takehome_STUDENT.sql and prints the numbers the
self-check quotes. Load it into the running warehouse with:
    psql -d kalpa -f content/W02/D3/data/C2_W02_D03_takehome_STUDENT.sql
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[4]
sys.path.insert(0, str(ROOT / "data"))
import generate_client_zero as gcz  # noqa: E402

SEED = 20261014          # the day's date, so the sample is reproducible and unlike the warehouse
TIE_AT = 19              # the three-way tie spans positions 19, 20 and 21 of Retail-Core
OUT = ROOT / "content/W02/D3/data/C2_W02_D03_takehome_STUDENT.sql"

HEADER = """-- Kalpa Retail, a second sample for the Week 2 Wednesday take-home.
-- Generated by content/W02/D3/internal/C2_W02_D03_takehome_data_INTERNAL.py from
-- data/generate_client_zero.py. Do not edit by hand.
-- It loads into its own schema, takehome, so the warehouse the day used stays as it was.
-- Load it with: psql -d kalpa -f content/W02/D3/data/C2_W02_D03_takehome_STUDENT.sql
-- Then query it as takehome.orders, takehome.customers and takehome.plan_line.
DROP SCHEMA IF EXISTS takehome CASCADE;
CREATE SCHEMA takehome;

CREATE TABLE takehome.customers (
    customer_id  text PRIMARY KEY,
    segment      text NOT NULL,
    city         text NOT NULL,
    country      text NOT NULL,
    joined_date  date NOT NULL
);

CREATE TABLE takehome.orders (
    order_id     text PRIMARY KEY,
    customer_id  text NOT NULL REFERENCES takehome.customers (customer_id),
    order_date   date NOT NULL,
    quarter      text NOT NULL,
    channel      text NOT NULL,
    amount       numeric(12, 2) NOT NULL,
    status       text NOT NULL
);

CREATE TABLE takehome.plan_line (
    week_start    date PRIMARY KEY,
    plan_revenue  numeric(14, 2) NOT NULL
);
"""

TABLES = [
    ("customers", ("customer_id", "segment", "city", "country", "joined_date")),
    ("orders", ("order_id", "customer_id", "order_date", "quarter", "channel", "amount", "status")),
    ("plan_line", ("week_start", "plan_revenue")),
]


def q2_spend(orders, members):
    spend = {}
    for o in orders:
        if o["quarter"] == "Q2" and o["customer_id"] in members:
            spend[o["customer_id"]] = spend.get(o["customer_id"], 0) + o["amount"]
    return sorted(spend.items(), key=lambda kv: (-kv[1], kv[0]))


def plant_tie(tables):
    """Lift the 20th and 21st Retail-Core members to the 19th's Q2 revenue, then settle Q2."""
    seg = {c["customer_id"]: c["segment"] for c in tables["customers"]}
    core = {c for c, s in seg.items() if s == "Retail-Core"}
    ranked = q2_spend(tables["orders"], core)
    target = ranked[TIE_AT - 1][1]
    added = 0
    for cid, spend in ranked[TIE_AT:TIE_AT + 2]:
        theirs = [o for o in tables["orders"] if o["customer_id"] == cid and o["quarter"] == "Q2"]
        theirs[0]["amount"] += target - spend
        added += target - spend
    # Take the same rupees off the quarter's last Business order, so Q2 still lands on the contract.
    business = [o for o in tables["orders"]
                if o["quarter"] == "Q2" and seg[o["customer_id"]] == "Business"]
    business[-1]["amount"] -= added
    return [cid for cid, _ in ranked[TIE_AT - 1:TIE_AT + 2]], target


def main():
    gcz.SEED = SEED
    tables = gcz.build_v4()
    tied, amount = plant_tie(tables)
    out = [HEADER]
    for name, cols in TABLES:
        out.append(f"COPY takehome.{name} ({', '.join(cols)}) FROM stdin;")
        for r in tables[name]:
            out.append("\t".join(str(r[c]) for c in cols))
        out.append("\\.")
        out.append("")
    out.append("-- Row counts this file must load:")
    for name, _ in TABLES:
        out.append(f"--   {name}: {len(tables[name])}")
    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"Retail-Core tie at positions {TIE_AT} to {TIE_AT + 2}: {', '.join(tied)} on Rs {amount:,}")
    print(f"falling-spend ladder members: {', '.join(tables['_meta']['falling'])}")
    q2 = sum(o["amount"] for o in tables["orders"] if o["quarter"] == "Q2")
    print(f"orders {len(tables['orders'])}, Q2 booked Rs {q2:,}")


if __name__ == "__main__":
    main()

# Test inputs and expected outcomes
# --------------------------------
# python3 content/W02/D3/internal/C2_W02_D03_takehome_data_INTERNAL.py
#     Writes the take-home SQL file and prints the three tied Retail-Core members and their Q2
#     revenue, the three falling-ladder members, and "orders 1000, Q2 booked Rs 98,400,000".
# psql -d kalpa -f content/W02/D3/data/C2_W02_D03_takehome_STUDENT.sql
#     Creates the takehome schema with 340 customers, 1,000 orders and 13 plan weeks, and leaves
#     the public warehouse untouched.
# Run twice in a row
#     Writes a byte-identical file, since the seed is fixed.
