-- Kalpa Retail, a second sample for the Week 2 Wednesday take-home.
-- Generated by content/W02/D3/internal/C2_W02_D03_takehome_data_INTERNAL.py from
-- data/generate_client_zero.py. Do not edit by hand.
-- It loads into its own schema, takehome, so the warehouse the day used stays as it was.
-- Load it with: psql -d kalpa -f content/W02/D3/data/C2_W02_D03_takehome_STUDENT.sql
-- Then query it as takehome.orders, takehome.customers and takehome.plan_line.
DROP SCHEMA IF EXISTS takehome CASCADE;
CREATE SCHEMA takehome;

CREATE TABLE takehome.customers (
    customer_id  text PRIMARY KEY,
    segment      text NOT NULL,
    city         text NOT NULL,
    country      text NOT NULL,
    joined_date  date NOT NULL
);

CREATE TABLE takehome.orders (
    order_id     text PRIMARY KEY,
    customer_id  text NOT NULL REFERENCES takehome.customers (customer_id),
    order_date   date NOT NULL,
    quarter      text NOT NULL,
    channel      text NOT NULL,
    amount       numeric(12, 2) NOT NULL,
    status       text NOT NULL
);

CREATE TABLE takehome.plan_line (
    week_start    date PRIMARY KEY,
    plan_revenue  numeric(14, 2) NOT NULL
);

COPY takehome.customers (customer_id, segment, city, country, joined_date) FROM stdin;
C-0001	Retail-Core	Mumbai	IN	2024-02-28
C-0002	Retail-Core	Chennai	IN	2025-09-26
C-0003	Retail-Core	Bengaluru	IN	2023-01-20
C-0004	Retail-Core	Delhi	IN	2024-10-28
C-0005	Retail-Core	Mumbai	IN	2025-09-17
C-0006	Retail-Core	Bengaluru	IN	2023-03-21
C-0007	Retail-Core	Bengaluru	IN	2023-10-26
C-0008	Retail-Core	Mumbai	IN	2025-04-18
C-0009	Retail-Core	Hyderabad	IN	2023-12-04
C-0010	Retail-Core	Pune	IN	2025-08-01
C-0011	Retail-Core	Bengaluru	IN	2025-02-23
C-0012	Retail-Core	Mumbai	IN	2023-11-19
C-0013	Retail-Core	Bengaluru	IN	2025-01-11
C-0014	Retail-Core	Hyderabad	IN	2025-02-10
C-0015	Retail-Core	Bengaluru	IN	2025-01-03
C-0016	Retail-Core	Pune	IN	2024-09-08
C-0017	Retail-Core	Pune	IN	2024-08-17
C-0018	Retail-Core	Chennai	IN	2025-04-01
C-0019	Retail-Core	Pune	IN	2025-08-19
C-0020	Retail-Core	Pune	IN	2023-04-24
C-0021	Retail-Core	Bengaluru	IN	2023-09-04
C-0022	Retail-Core	Delhi	IN	2024-04-02
C-0023	Retail-Core	Bengaluru	IN	2024-06-23
C-0024	Retail-Core	Chennai	IN	2023-02-25
C-0025	Retail-Core	Hyderabad	IN	2023-10-08
C-0026	Retail-Core	Mumbai	IN	2023-09-20
C-0027	Retail-Core	Bengaluru	IN	2025-11-12
C-0028	Retail-Core	Hyderabad	IN	2025-04-14
C-0029	Retail-Core	Hyderabad	IN	2024-03-20
C-0030	Retail-Core	Chennai	IN	2024-04-26
C-0031	Retail-Core	Hyderabad	IN	2024-11-13
C-0032	Retail-Core	Chennai	IN	2024-02-01
C-0033	Retail-Core	Mumbai	IN	2023-01-17
C-0034	Retail-Core	Hyderabad	IN	2025-06-24
C-0035	Retail-Core	Mumbai	IN	2024-07-02
C-0036	Retail-Core	Chennai	IN	2025-07-18
C-0037	Retail-Core	Chennai	IN	2024-09-27
C-0038	Retail-Core	Mumbai	IN	2024-02-18
C-0039	Retail-Core	Chennai	IN	2023-03-05
C-0040	Retail-Core	Bengaluru	IN	2024-04-05
C-0041	Retail-Core	Mumbai	IN	2025-01-27
C-0042	Retail-Core	Hyderabad	IN	2023-10-23
C-0043	Retail-Core	Chennai	IN	2023-05-20
C-0044	Retail-Core	Pune	IN	2025-05-20
C-0045	Retail-Core	Chennai	IN	2024-07-11
C-0046	Retail-Core	Hyderabad	IN	2025-07-24
C-0047	Retail-Core	Mumbai	IN	2023-10-06
C-0048	Retail-Core	Hyderabad	IN	2025-10-11
C-0049	Retail-Core	Hyderabad	IN	2024-01-22
C-0050	Retail-Core	Hyderabad	IN	2024-12-25
C-0051	Retail-Core	Bengaluru	IN	2024-12-27
C-0052	Retail-Core	Mumbai	IN	2023-03-08
C-0053	Retail-Core	Pune	IN	2025-12-19
C-0054	Retail-Core	Delhi	IN	2025-07-02
C-0055	Retail-Core	Mumbai	IN	2024-05-11
C-0056	Retail-Core	Delhi	IN	2024-01-09
C-0057	Retail-Core	Hyderabad	IN	2025-01-27
C-0058	Retail-Core	Mumbai	IN	2023-12-27
C-0059	Retail-Core	Hyderabad	IN	2025-11-02
C-0060	Retail-Core	Bengaluru	IN	2025-12-03
C-0061	Retail-Core	Bengaluru	IN	2025-10-17
C-0062	Retail-Core	Pune	IN	2024-12-09
C-0063	Retail-Core	Mumbai	IN	2023-07-20
C-0064	Retail-Core	Chennai	IN	2024-10-06
C-0065	Retail-Core	Pune	IN	2025-03-07
C-0066	Retail-Core	Hyderabad	IN	2024-12-28
C-0067	Retail-Core	Mumbai	IN	2025-11-23
C-0068	Retail-Core	Mumbai	IN	2025-03-24
C-0069	Retail-Core	Hyderabad	IN	2025-01-15
C-0070	Retail-Core	Bengaluru	IN	2025-08-02
C-0071	Retail-Core	Bengaluru	IN	2024-09-06
C-0072	Retail-Core	Bengaluru	IN	2024-10-10
C-0073	Retail-Core	Pune	IN	2023-02-17
C-0074	Retail-Core	Delhi	IN	2023-11-15
C-0075	Retail-Core	Chennai	IN	2023-08-24
C-0076	Retail-Core	Hyderabad	IN	2025-04-22
C-0077	Retail-Core	Mumbai	IN	2024-02-20
C-0078	Retail-Core	Mumbai	IN	2024-06-22
C-0079	Retail-Core	Hyderabad	IN	2023-03-06
C-0080	Retail-Core	Bengaluru	IN	2023-07-20
C-0081	Retail-Core	Pune	IN	2025-01-06
C-0082	Retail-Core	Delhi	IN	2023-09-23
C-0083	Retail-Core	Pune	IN	2024-02-23
C-0084	Retail-Core	Mumbai	IN	2023-07-04
C-0085	Retail-Core	Bengaluru	IN	2025-06-26
C-0086	Retail-Core	Mumbai	IN	2023-12-01
C-0087	Retail-Core	Delhi	IN	2024-01-27
C-0088	Retail-Core	Hyderabad	IN	2024-11-21
C-0089	Retail-Core	Bengaluru	IN	2023-12-18
C-0090	Retail-Core	Chennai	IN	2024-03-13
C-0091	Retail-Core	Bengaluru	IN	2023-05-02
C-0092	Retail-Core	Chennai	IN	2024-07-02
C-0093	Retail-Core	Pune	IN	2025-07-10
C-0094	Retail-Core	Bengaluru	IN	2024-05-09
C-0095	Retail-Core	Chennai	IN	2025-01-24
C-0096	Retail-Core	Delhi	IN	2023-09-26
C-0097	Retail-Core	Delhi	IN	2024-03-07
C-0098	Retail-Core	Chennai	IN	2025-09-27
C-0099	Retail-Core	Mumbai	IN	2024-10-21
C-0100	Retail-Core	Mumbai	IN	2025-08-07
C-0101	Retail-Core	Bengaluru	IN	2024-10-18
C-0102	Retail-Core	Chennai	IN	2025-04-16
C-0103	Retail-Core	Chennai	IN	2024-03-14
C-0104	Retail-Core	Hyderabad	IN	2023-04-28
C-0105	Retail-Core	Chennai	IN	2024-06-10
C-0106	Retail-Core	Mumbai	IN	2023-01-14
C-0107	Retail-Core	Chennai	IN	2023-07-15
C-0108	Retail-Core	Mumbai	IN	2024-06-17
C-0109	Retail-Core	Hyderabad	IN	2023-08-28
C-0110	Retail-Core	Mumbai	IN	2023-03-08
C-0111	Retail-Core	Delhi	IN	2023-11-27
C-0112	Retail-Core	Pune	IN	2023-02-12
C-0113	Retail-Core	Hyderabad	IN	2025-01-06
C-0114	Retail-Core	Delhi	IN	2024-09-11
C-0115	Retail-Core	Mumbai	IN	2024-01-01
C-0116	Retail-Core	Bengaluru	IN	2023-04-01
C-0117	Retail-Core	Bengaluru	IN	2023-10-09
C-0118	Retail-Core	Chennai	IN	2025-06-22
C-0119	Retail-Core	Pune	IN	2024-04-19
C-0120	Retail-Core	Chennai	IN	2024-03-28
C-0121	Retail-Core	Hyderabad	IN	2023-01-22
C-0122	Retail-Core	Mumbai	IN	2025-10-15
C-0123	Retail-Core	Hyderabad	IN	2024-07-11
C-0124	Retail-Core	Hyderabad	IN	2024-04-17
C-0125	Retail-Core	Pune	IN	2025-12-24
C-0126	Retail-Core	Mumbai	IN	2025-04-16
C-0127	Retail-Core	Hyderabad	IN	2025-03-02
C-0128	Retail-Core	Mumbai	IN	2023-01-04
C-0129	Retail-Core	Mumbai	IN	2023-07-11
C-0130	Retail-Core	Bengaluru	IN	2024-11-02
C-0131	Retail-Core	Hyderabad	IN	2025-02-21
C-0132	Retail-Core	Hyderabad	IN	2024-03-11
C-0133	Retail-Core	Chennai	IN	2023-08-21
C-0134	Retail-Core	Pune	IN	2023-02-25
C-0135	Retail-Core	Bengaluru	IN	2023-04-27
C-0136	Retail-Core	Mumbai	IN	2023-04-15
C-0137	Retail-Core	Delhi	IN	2024-06-11
C-0138	Retail-Core	Bengaluru	IN	2024-02-04
C-0139	Retail-Core	Mumbai	IN	2025-07-25
C-0140	Retail-Core	Hyderabad	IN	2025-08-09
C-0141	Retail-Core	Pune	IN	2025-09-21
C-0142	Retail-Core	Chennai	IN	2024-03-16
C-0143	Retail-Core	Pune	IN	2025-10-12
C-0144	Retail-Core	Bengaluru	IN	2023-10-10
C-0145	Retail-Core	Pune	IN	2025-11-19
C-0146	Retail-Core	Bengaluru	IN	2023-03-08
C-0147	Retail-Core	Bengaluru	IN	2023-04-24
C-0148	Retail-Core	Chennai	IN	2024-05-15
C-0149	Retail-Core	Pune	IN	2024-10-07
C-0150	Retail-Core	Chennai	IN	2025-08-03
C-0151	Retail-Plus	Hyderabad	IN	2025-07-26
C-0152	Retail-Plus	Mumbai	IN	2023-12-03
C-0153	Retail-Plus	Bengaluru	IN	2024-06-17
C-0154	Retail-Plus	Pune	IN	2024-11-01
C-0155	Retail-Plus	Bengaluru	IN	2025-01-03
C-0156	Retail-Plus	Hyderabad	IN	2025-03-26
C-0157	Retail-Plus	Delhi	IN	2025-04-14
C-0158	Retail-Plus	Bengaluru	IN	2024-07-23
C-0159	Retail-Plus	Chennai	IN	2023-09-20
C-0160	Retail-Plus	Chennai	IN	2025-09-19
C-0161	Retail-Plus	Bengaluru	IN	2025-03-09
C-0162	Retail-Plus	Chennai	IN	2025-07-12
C-0163	Retail-Plus	Pune	IN	2025-03-12
C-0164	Retail-Plus	Pune	IN	2023-06-07
C-0165	Retail-Plus	Bengaluru	IN	2025-01-03
C-0166	Retail-Plus	Mumbai	IN	2023-03-09
C-0167	Retail-Plus	Bengaluru	IN	2024-06-01
C-0168	Retail-Plus	Chennai	IN	2025-10-28
C-0169	Retail-Plus	Delhi	IN	2024-07-01
C-0170	Retail-Plus	Bengaluru	IN	2025-12-17
C-0171	Retail-Plus	Pune	IN	2023-09-08
C-0172	Retail-Plus	Bengaluru	IN	2024-08-02
C-0173	Retail-Plus	Chennai	IN	2025-08-23
C-0174	Retail-Plus	Chennai	IN	2025-06-12
C-0175	Retail-Plus	Hyderabad	IN	2025-05-20
C-0176	Retail-Plus	Mumbai	IN	2023-11-23
C-0177	Retail-Plus	Delhi	IN	2023-01-10
C-0178	Retail-Plus	Bengaluru	IN	2023-07-18
C-0179	Retail-Plus	Hyderabad	IN	2025-07-14
C-0180	Retail-Plus	Delhi	IN	2024-12-06
C-0181	Retail-Plus	Mumbai	IN	2023-02-13
C-0182	Retail-Plus	Chennai	IN	2025-04-03
C-0183	Retail-Plus	Delhi	IN	2024-02-06
C-0184	Retail-Plus	Delhi	IN	2025-01-10
C-0185	Retail-Plus	Hyderabad	IN	2024-09-28
C-0186	Retail-Plus	Bengaluru	IN	2024-08-03
C-0187	Retail-Plus	Bengaluru	IN	2025-11-26
C-0188	Retail-Plus	Delhi	IN	2025-10-24
C-0189	Retail-Plus	Chennai	IN	2025-10-02
C-0190	Retail-Plus	Bengaluru	IN	2025-04-14
C-0191	Retail-Plus	Mumbai	IN	2024-10-28
C-0192	Retail-Plus	Pune	IN	2023-06-27
C-0193	Retail-Plus	Pune	IN	2025-09-20
C-0194	Retail-Plus	Bengaluru	IN	2024-12-02
C-0195	Retail-Plus	Bengaluru	IN	2023-08-28
C-0196	Retail-Plus	Chennai	IN	2024-06-26
C-0197	Retail-Plus	Chennai	IN	2024-10-21
C-0198	Retail-Plus	Hyderabad	IN	2024-04-09
C-0199	Retail-Plus	Delhi	IN	2023-10-12
C-0200	Retail-Plus	Bengaluru	IN	2023-02-28
C-0201	Retail-Plus	Pune	IN	2025-03-04
C-0202	Retail-Plus	Pune	IN	2024-07-15
C-0203	Retail-Plus	Bengaluru	IN	2025-09-22
C-0204	Retail-Plus	Delhi	IN	2023-08-25
C-0205	Retail-Plus	Mumbai	IN	2025-01-07
C-0206	Retail-Plus	Delhi	IN	2023-06-14
C-0207	Retail-Plus	Delhi	IN	2023-03-24
C-0208	Retail-Plus	Delhi	IN	2025-03-12
C-0209	Retail-Plus	Mumbai	IN	2024-02-14
C-0210	Retail-Plus	Chennai	IN	2023-09-06
C-0211	Retail-Plus	Hyderabad	IN	2024-02-01
C-0212	Retail-Plus	Mumbai	IN	2024-02-22
C-0213	Retail-Plus	Bengaluru	IN	2024-03-15
C-0214	Retail-Plus	Bengaluru	IN	2025-10-07
C-0215	Retail-Plus	Bengaluru	IN	2023-11-06
C-0216	Retail-Plus	Bengaluru	IN	2025-04-22
C-0217	Retail-Plus	Pune	IN	2025-11-05
C-0218	Retail-Plus	Mumbai	IN	2024-10-28
C-0219	Retail-Plus	Bengaluru	IN	2023-02-28
C-0220	Retail-Plus	Mumbai	IN	2023-09-27
C-0221	Retail-Plus	Mumbai	IN	2023-11-17
C-0222	Retail-Plus	Pune	IN	2024-07-06
C-0223	Retail-Plus	Hyderabad	IN	2024-06-16
C-0224	Retail-Plus	Pune	IN	2025-12-06
C-0225	Retail-Plus	Hyderabad	IN	2024-06-02
C-0226	Retail-Plus	Chennai	IN	2024-04-08
C-0227	Retail-Plus	Mumbai	IN	2024-05-24
C-0228	Retail-Plus	Delhi	IN	2025-07-05
C-0229	Retail-Plus	Hyderabad	IN	2024-09-08
C-0230	Retail-Plus	Hyderabad	IN	2024-05-07
C-0231	Retail-Plus	Hyderabad	IN	2024-07-05
C-0232	Retail-Plus	Mumbai	IN	2024-12-02
C-0233	Retail-Plus	Bengaluru	IN	2024-06-06
C-0234	Retail-Plus	Chennai	IN	2025-07-05
C-0235	Retail-Plus	Pune	IN	2024-04-20
C-0236	Retail-Plus	Pune	IN	2023-02-01
C-0237	Retail-Plus	Hyderabad	IN	2023-01-04
C-0238	Retail-Plus	Bengaluru	IN	2025-10-23
C-0239	Retail-Plus	Chennai	IN	2024-09-27
C-0240	Retail-Plus	Chennai	IN	2023-04-13
C-0241	Retail-Plus	Hyderabad	IN	2025-02-25
C-0242	Retail-Plus	Delhi	IN	2024-01-13
C-0243	Retail-Plus	Hyderabad	IN	2024-12-06
C-0244	Retail-Plus	Delhi	IN	2025-08-19
C-0245	Retail-Plus	Chennai	IN	2025-11-25
C-0246	Retail-Plus	Chennai	IN	2024-05-09
C-0247	Retail-Plus	Delhi	IN	2024-07-04
C-0248	Retail-Plus	Delhi	IN	2023-11-09
C-0249	Retail-Plus	Bengaluru	IN	2024-03-04
C-0250	Retail-Plus	Delhi	IN	2023-11-10
C-0251	Retail-Plus	Hyderabad	IN	2025-11-25
C-0252	Retail-Plus	Bengaluru	IN	2023-11-04
C-0253	Retail-Plus	Mumbai	IN	2025-05-26
C-0254	Retail-Plus	Pune	IN	2024-03-24
C-0255	Retail-Plus	Hyderabad	IN	2024-03-01
C-0256	Retail-Plus	Mumbai	IN	2024-05-22
C-0257	Retail-Plus	Pune	IN	2024-11-02
C-0258	Retail-Plus	Pune	IN	2024-10-09
C-0259	Retail-Plus	Delhi	IN	2025-07-09
C-0260	Retail-Plus	Bengaluru	IN	2024-01-27
C-0261	Retail-Plus	Mumbai	IN	2025-10-14
C-0262	Retail-Plus	Chennai	IN	2023-01-12
C-0263	Retail-Plus	Hyderabad	IN	2023-06-12
C-0264	Retail-Plus	Pune	IN	2025-09-10
C-0265	Retail-Plus	Bengaluru	IN	2024-03-02
C-0266	Retail-Plus	Delhi	IN	2024-05-22
C-0267	Retail-Plus	Bengaluru	IN	2024-08-17
C-0268	Retail-Plus	Bengaluru	IN	2023-09-09
C-0269	Retail-Plus	Bengaluru	IN	2023-07-16
C-0270	Retail-Plus	Chennai	IN	2025-11-21
C-0271	Business	Pune	IN	2024-07-06
C-0272	Business	Hyderabad	IN	2025-10-05
C-0273	Business	Pune	IN	2023-07-21
C-0274	Business	Bengaluru	IN	2025-05-17
C-0275	Business	Mumbai	IN	2024-02-25
C-0276	Business	Delhi	IN	2024-07-13
C-0277	Business	Pune	IN	2025-05-25
C-0278	Business	Mumbai	IN	2025-04-02
C-0279	Business	Mumbai	IN	2023-02-04
C-0280	Business	Mumbai	IN	2024-01-01
C-0281	Business	Mumbai	IN	2023-07-10
C-0282	Business	Chennai	IN	2025-09-02
C-0283	Business	Hyderabad	IN	2024-01-12
C-0284	Business	Hyderabad	IN	2025-11-15
C-0285	Business	Chennai	IN	2023-05-06
C-0286	Business	Chennai	IN	2023-10-18
C-0287	Business	Delhi	IN	2023-02-26
C-0288	Business	Bengaluru	IN	2025-05-03
C-0289	Business	Pune	IN	2023-05-16
C-0290	Business	Mumbai	IN	2023-05-27
C-0291	Business	Pune	IN	2023-01-26
C-0292	Business	Chennai	IN	2023-03-02
C-0293	Business	Pune	IN	2023-09-05
C-0294	Business	Hyderabad	IN	2024-10-07
C-0295	Business	Bengaluru	IN	2024-04-01
C-0296	Business	Mumbai	IN	2024-07-06
C-0297	Business	Delhi	IN	2023-09-17
C-0298	Business	Mumbai	IN	2023-10-13
C-0299	Business	Delhi	IN	2023-07-26
C-0300	Business	Mumbai	IN	2023-09-22
C-0301	Business	Delhi	IN	2024-09-02
C-0302	Business	Hyderabad	IN	2024-01-12
C-0303	Business	Delhi	IN	2023-12-06
C-0304	Business	Mumbai	IN	2023-12-11
C-0305	Business	Bengaluru	IN	2025-11-23
C-0306	Business	Delhi	IN	2024-09-06
C-0307	Business	Bengaluru	IN	2024-02-16
C-0308	Business	Hyderabad	IN	2024-09-17
C-0309	Business	Hyderabad	IN	2025-01-28
C-0310	Business	Hyderabad	IN	2024-07-23
C-0311	Student	Mumbai	IN	2023-12-12
C-0312	Student	Pune	IN	2023-07-28
C-0313	Student	Bengaluru	IN	2025-04-28
C-0314	Student	Chennai	IN	2023-10-18
C-0315	Student	Chennai	IN	2023-05-13
C-0316	Student	Pune	IN	2025-06-18
C-0317	Student	Pune	IN	2023-12-02
C-0318	Student	Pune	IN	2024-10-21
C-0319	Student	Mumbai	IN	2025-03-16
C-0320	Student	Hyderabad	IN	2023-09-09
C-0321	Student	Pune	IN	2024-02-23
C-0322	Student	Bengaluru	IN	2024-11-10
C-0323	Student	Delhi	IN	2024-02-26
C-0324	Student	Pune	IN	2024-07-19
C-0325	Student	Mumbai	IN	2025-10-14
C-0326	Student	Bengaluru	IN	2023-08-16
C-0327	Student	Pune	IN	2024-05-19
C-0328	Student	Hyderabad	IN	2023-04-26
C-0329	Student	Delhi	IN	2024-03-25
C-0330	Student	Mumbai	IN	2023-08-19
C-0331	Student	Delhi	IN	2025-03-18
C-0332	Student	Bengaluru	IN	2025-10-04
C-0333	Student	Mumbai	IN	2023-12-23
C-0334	Student	Pune	IN	2025-02-12
C-0335	Student	Bengaluru	IN	2025-01-22
C-0336	Student	Mumbai	IN	2024-05-23
C-0337	Student	Delhi	IN	2024-06-17
C-0338	Student	Hyderabad	IN	2023-06-15
C-0339	Student	Chennai	IN	2024-09-23
C-0340	Student	Hyderabad	IN	2024-10-14
\.

COPY takehome.orders (order_id, customer_id, order_date, quarter, channel, amount, status) FROM stdin;
KR-00001	C-0334	2026-04-04	Q1	app	1000	returned
KR-00002	C-0311	2026-05-12	Q1	app	400	cancelled
KR-00003	C-0325	2026-06-21	Q1	web	1110	delivered
KR-00004	C-0317	2026-04-21	Q1	web	690	delivered
KR-00005	C-0317	2026-05-28	Q1	web	420	returned
KR-00006	C-0340	2026-06-11	Q1	web	1440	delivered
KR-00007	C-0340	2026-04-25	Q1	web	1190	delivered
KR-00008	C-0323	2026-05-01	Q1	store	850	delivered
KR-00009	C-0333	2026-06-09	Q1	store	780	delivered
KR-00010	C-0312	2026-04-22	Q1	store	570	delivered
KR-00011	C-0313	2026-05-08	Q1	store	670	delivered
KR-00012	C-0316	2026-06-10	Q1	store	710	delivered
KR-00013	C-0333	2026-04-08	Q1	web	1490	cancelled
KR-00014	C-0314	2026-05-11	Q1	app	1070	delivered
KR-00015	C-0336	2026-06-27	Q1	store	1130	delivered
KR-00016	C-0313	2026-04-17	Q1	web	640	delivered
KR-00017	C-0314	2026-05-11	Q1	store	600	delivered
KR-00018	C-0337	2026-06-27	Q1	store	820	delivered
KR-00019	C-0320	2026-04-13	Q1	web	1490	cancelled
KR-00020	C-0311	2026-05-18	Q1	store	1490	delivered
KR-00021	C-0333	2026-06-15	Q1	app	1300	cancelled
KR-00022	C-0324	2026-04-16	Q1	web	980	delivered
KR-00023	C-0319	2026-05-08	Q1	web	670	delivered
KR-00024	C-0313	2026-06-04	Q1	web	1440	delivered
KR-00025	C-0319	2026-04-08	Q1	app	1490	delivered
KR-00026	C-0330	2026-05-28	Q1	web	1310	returned
KR-00027	C-0317	2026-06-06	Q1	web	1420	returned
KR-00028	C-0301	2026-04-04	Q1	store	565000	returned
KR-00029	C-0294	2026-05-10	Q1	app	241000	delivered
KR-00030	C-0272	2026-06-03	Q1	store	262000	delivered
KR-00031	C-0280	2026-04-02	Q1	store	1187000	returned
KR-00032	C-0292	2026-05-28	Q1	store	1334000	delivered
KR-00033	C-0273	2026-06-15	Q1	app	940000	delivered
KR-00034	C-0282	2026-04-11	Q1	store	1632000	returned
KR-00035	C-0309	2026-05-21	Q1	app	411000	delivered
KR-00036	C-0279	2026-06-08	Q1	app	897000	delivered
KR-00037	C-0274	2026-04-17	Q1	app	1452000	cancelled
KR-00038	C-0296	2026-05-16	Q1	store	453000	cancelled
KR-00039	C-0289	2026-06-02	Q1	app	1602000	delivered
KR-00040	C-0281	2026-04-15	Q1	web	1046000	delivered
KR-00041	C-0287	2026-05-22	Q1	web	1440000	cancelled
KR-00042	C-0280	2026-06-23	Q1	store	809000	delivered
KR-00043	C-0278	2026-04-17	Q1	web	1448000	delivered
KR-00044	C-0290	2026-05-15	Q1	store	1750000	delivered
KR-00045	C-0281	2026-06-19	Q1	web	548000	cancelled
KR-00046	C-0279	2026-04-11	Q1	app	1683000	delivered
KR-00047	C-0310	2026-05-19	Q1	store	1085000	returned
KR-00048	C-0281	2026-06-23	Q1	web	895000	delivered
KR-00049	C-0282	2026-04-02	Q1	app	935000	delivered
KR-00050	C-0293	2026-05-09	Q1	app	686000	cancelled
KR-00051	C-0290	2026-06-28	Q1	store	1363000	delivered
KR-00052	C-0281	2026-04-17	Q1	app	1751000	cancelled
KR-00053	C-0299	2026-05-01	Q1	store	1003000	delivered
KR-00054	C-0280	2026-06-26	Q1	web	528000	returned
KR-00055	C-0282	2026-04-24	Q1	web	1227000	returned
KR-00056	C-0307	2026-05-01	Q1	app	1567000	delivered
KR-00057	C-0276	2026-06-14	Q1	app	262000	delivered
KR-00058	C-0294	2026-04-22	Q1	store	470000	delivered
KR-00059	C-0278	2026-05-22	Q1	app	1617000	delivered
KR-00060	C-0274	2026-06-28	Q1	store	551000	delivered
KR-00061	C-0297	2026-04-17	Q1	app	577000	delivered
KR-00062	C-0301	2026-05-20	Q1	app	1378000	delivered
KR-00063	C-0298	2026-06-11	Q1	store	621000	returned
KR-00064	C-0290	2026-04-25	Q1	web	1684000	delivered
KR-00065	C-0272	2026-05-01	Q1	app	354000	returned
KR-00066	C-0277	2026-06-28	Q1	store	281000	delivered
KR-00067	C-0309	2026-04-07	Q1	web	1587000	delivered
KR-00068	C-0279	2026-05-13	Q1	web	257000	delivered
KR-00069	C-0283	2026-06-17	Q1	store	605000	cancelled
KR-00070	C-0288	2026-04-08	Q1	app	1267000	cancelled
KR-00071	C-0301	2026-05-10	Q1	store	500000	delivered
KR-00072	C-0273	2026-06-08	Q1	store	1167000	cancelled
KR-00073	C-0272	2026-04-22	Q1	store	631000	delivered
KR-00074	C-0294	2026-05-26	Q1	web	700000	cancelled
KR-00075	C-0282	2026-06-20	Q1	web	1392000	cancelled
KR-00076	C-0297	2026-04-19	Q1	web	1793000	delivered
KR-00077	C-0272	2026-05-07	Q1	web	541000	delivered
KR-00078	C-0282	2026-06-16	Q1	app	1798000	delivered
KR-00079	C-0275	2026-04-22	Q1	store	378000	delivered
KR-00080	C-0281	2026-05-27	Q1	web	359000	delivered
KR-00081	C-0283	2026-06-14	Q1	app	701000	returned
KR-00082	C-0309	2026-04-14	Q1	store	1229000	delivered
KR-00083	C-0283	2026-05-15	Q1	app	826000	cancelled
KR-00084	C-0284	2026-06-02	Q1	web	208000	delivered
KR-00085	C-0297	2026-04-09	Q1	app	1030000	delivered
KR-00086	C-0282	2026-05-16	Q1	web	1536000	delivered
KR-00087	C-0299	2026-06-22	Q1	store	1154000	delivered
KR-00088	C-0274	2026-04-26	Q1	store	1580000	delivered
KR-00089	C-0273	2026-05-24	Q1	app	1520000	delivered
KR-00090	C-0277	2026-06-10	Q1	app	793000	delivered
KR-00091	C-0272	2026-04-28	Q1	app	591000	delivered
KR-00092	C-0279	2026-05-20	Q1	app	1127000	delivered
KR-00093	C-0290	2026-06-07	Q1	app	1794000	delivered
KR-00094	C-0281	2026-04-25	Q1	app	822000	delivered
KR-00095	C-0282	2026-05-23	Q1	app	390000	returned
KR-00096	C-0294	2026-06-24	Q1	app	1674000	delivered
KR-00097	C-0278	2026-04-26	Q1	app	452000	delivered
KR-00098	C-0277	2026-05-09	Q1	app	496000	delivered
KR-00099	C-0306	2026-06-21	Q1	store	1005000	returned
KR-00100	C-0280	2026-04-20	Q1	store	1063000	delivered
KR-00101	C-0272	2026-05-07	Q1	web	1034000	delivered
KR-00102	C-0285	2026-06-02	Q1	web	1627000	delivered
KR-00103	C-0310	2026-04-17	Q1	web	1358000	delivered
KR-00104	C-0291	2026-05-27	Q1	web	1024000	cancelled
KR-00105	C-0275	2026-06-16	Q1	store	1372000	delivered
KR-00106	C-0283	2026-04-16	Q1	web	1061000	cancelled
KR-00107	C-0279	2026-05-01	Q1	web	1582000	returned
KR-00108	C-0278	2026-06-10	Q1	web	1351000	delivered
KR-00109	C-0277	2026-04-09	Q1	app	716000	returned
KR-00110	C-0286	2026-05-25	Q1	app	1047000	delivered
KR-00111	C-0290	2026-06-08	Q1	web	262000	delivered
KR-00112	C-0283	2026-04-17	Q1	web	817000	delivered
KR-00113	C-0309	2026-05-16	Q1	store	1390000	delivered
KR-00114	C-0281	2026-06-03	Q1	app	1067000	delivered
KR-00115	C-0292	2026-04-06	Q1	store	907000	delivered
KR-00116	C-0297	2026-05-24	Q1	web	783000	delivered
KR-00117	C-0303	2026-06-28	Q1	web	908000	cancelled
KR-00118	C-0282	2026-04-02	Q1	web	1442000	returned
KR-00119	C-0277	2026-05-13	Q1	store	1273000	returned
KR-00120	C-0278	2026-06-13	Q1	app	476000	delivered
KR-00121	C-0296	2026-04-17	Q1	web	1758000	delivered
KR-00122	C-0280	2026-05-08	Q1	web	1301000	delivered
KR-00123	C-0300	2026-06-25	Q1	store	517000	delivered
KR-00124	C-0275	2026-04-17	Q1	web	-1447460	delivered
KR-00125	C-0158	2026-04-18	Q1	store	3200	delivered
KR-00126	C-0180	2026-05-15	Q1	store	2440	delivered
KR-00127	C-0249	2026-06-06	Q1	store	2490	delivered
KR-00128	C-0259	2026-04-23	Q1	app	3220	delivered
KR-00129	C-0165	2026-05-19	Q1	app	1460	delivered
KR-00130	C-0182	2026-06-15	Q1	web	3970	returned
KR-00131	C-0184	2026-04-23	Q1	app	2970	delivered
KR-00132	C-0158	2026-05-03	Q1	store	2320	delivered
KR-00133	C-0215	2026-06-10	Q1	web	3010	delivered
KR-00134	C-0252	2026-04-26	Q1	web	1630	delivered
KR-00135	C-0250	2026-05-03	Q1	app	2820	delivered
KR-00136	C-0157	2026-06-01	Q1	web	2040	cancelled
KR-00137	C-0256	2026-04-11	Q1	store	1330	delivered
KR-00138	C-0161	2026-05-09	Q1	store	3090	delivered
KR-00139	C-0179	2026-06-27	Q1	web	2180	delivered
KR-00140	C-0177	2026-04-20	Q1	store	2190	returned
KR-00141	C-0172	2026-05-19	Q1	web	4070	delivered
KR-00142	C-0181	2026-06-21	Q1	store	1300	delivered
KR-00143	C-0166	2026-04-07	Q1	store	3750	delivered
KR-00144	C-0207	2026-05-19	Q1	store	3330	delivered
KR-00145	C-0182	2026-06-06	Q1	store	3310	cancelled
KR-00146	C-0153	2026-04-04	Q1	store	3880	returned
KR-00147	C-0187	2026-05-17	Q1	web	1900	delivered
KR-00148	C-0199	2026-06-04	Q1	store	3690	delivered
KR-00149	C-0180	2026-04-25	Q1	web	4430	delivered
KR-00150	C-0239	2026-05-18	Q1	store	1510	delivered
KR-00151	C-0186	2026-06-14	Q1	web	2380	delivered
KR-00152	C-0168	2026-04-05	Q1	store	2310	delivered
KR-00153	C-0163	2026-05-10	Q1	app	1750	delivered
KR-00154	C-0156	2026-06-13	Q1	app	3410	cancelled
KR-00155	C-0158	2026-04-09	Q1	app	2860	delivered
KR-00156	C-0173	2026-05-18	Q1	store	2900	cancelled
KR-00157	C-0210	2026-06-25	Q1	app	4000	delivered
KR-00158	C-0219	2026-04-19	Q1	app	2170	delivered
KR-00159	C-0158	2026-05-21	Q1	store	2420	delivered
KR-00160	C-0165	2026-06-09	Q1	store	1970	delivered
KR-00161	C-0174	2026-04-24	Q1	app	2340	delivered
KR-00162	C-0261	2026-05-22	Q1	web	4250	returned
KR-00163	C-0263	2026-06-07	Q1	app	1770	delivered
KR-00164	C-0164	2026-04-14	Q1	app	1600	delivered
KR-00165	C-0168	2026-05-25	Q1	web	1400	delivered
KR-00166	C-0196	2026-06-23	Q1	store	1340	delivered
KR-00167	C-0211	2026-04-10	Q1	web	3690	delivered
KR-00168	C-0201	2026-05-28	Q1	app	2040	returned
KR-00169	C-0219	2026-06-23	Q1	web	2930	delivered
KR-00170	C-0240	2026-04-23	Q1	store	2290	delivered
KR-00171	C-0162	2026-05-20	Q1	store	1780	cancelled
KR-00172	C-0255	2026-06-09	Q1	app	1520	delivered
KR-00173	C-0162	2026-04-23	Q1	web	1820	delivered
KR-00174	C-0188	2026-05-05	Q1	web	1610	returned
KR-00175	C-0252	2026-06-15	Q1	web	2890	delivered
KR-00176	C-0186	2026-04-26	Q1	store	3490	returned
KR-00177	C-0178	2026-05-07	Q1	web	1310	delivered
KR-00178	C-0264	2026-06-24	Q1	app	1360	delivered
KR-00179	C-0174	2026-04-03	Q1	web	3700	delivered
KR-00180	C-0195	2026-05-03	Q1	app	3610	cancelled
KR-00181	C-0156	2026-06-20	Q1	web	3410	delivered
KR-00182	C-0158	2026-04-03	Q1	app	1510	delivered
KR-00183	C-0270	2026-05-20	Q1	app	3660	delivered
KR-00184	C-0229	2026-06-20	Q1	app	1500	delivered
KR-00185	C-0192	2026-04-25	Q1	store	1930	returned
KR-00186	C-0223	2026-05-22	Q1	web	3770	delivered
KR-00187	C-0190	2026-06-15	Q1	store	1500	delivered
KR-00188	C-0160	2026-04-16	Q1	store	1840	delivered
KR-00189	C-0234	2026-05-18	Q1	web	3470	returned
KR-00190	C-0174	2026-06-04	Q1	store	1260	delivered
KR-00191	C-0197	2026-04-14	Q1	app	2880	cancelled
KR-00192	C-0161	2026-05-10	Q1	store	2110	delivered
KR-00193	C-0181	2026-06-07	Q1	app	2630	delivered
KR-00194	C-0180	2026-04-03	Q1	web	3950	delivered
KR-00195	C-0224	2026-05-12	Q1	web	3490	delivered
KR-00196	C-0162	2026-06-28	Q1	web	1650	cancelled
KR-00197	C-0256	2026-04-21	Q1	app	1940	delivered
KR-00198	C-0268	2026-05-23	Q1	app	3990	returned
KR-00199	C-0151	2026-06-18	Q1	store	2610	delivered
KR-00200	C-0194	2026-04-21	Q1	app	3420	returned
KR-00201	C-0185	2026-05-05	Q1	app	4450	cancelled
KR-00202	C-0198	2026-06-03	Q1	app	2540	cancelled
KR-00203	C-0214	2026-04-05	Q1	web	1340	returned
KR-00204	C-0190	2026-05-08	Q1	store	1570	returned
KR-00205	C-0158	2026-06-01	Q1	store	2840	returned
KR-00206	C-0260	2026-04-20	Q1	web	3090	cancelled
KR-00207	C-0176	2026-05-08	Q1	store	4270	delivered
KR-00208	C-0186	2026-06-17	Q1	store	2530	delivered
KR-00209	C-0173	2026-04-18	Q1	web	1450	returned
KR-00210	C-0164	2026-05-12	Q1	web	4260	delivered
KR-00211	C-0152	2026-06-17	Q1	store	3230	returned
KR-00212	C-0175	2026-04-24	Q1	web	2810	delivered
KR-00213	C-0158	2026-05-23	Q1	web	4230	returned
KR-00214	C-0209	2026-06-10	Q1	store	2670	cancelled
KR-00215	C-0173	2026-04-23	Q1	store	3200	delivered
KR-00216	C-0216	2026-05-10	Q1	app	1430	delivered
KR-00217	C-0159	2026-06-16	Q1	web	1990	cancelled
KR-00218	C-0259	2026-04-13	Q1	web	1690	delivered
KR-00219	C-0175	2026-05-26	Q1	store	3270	returned
KR-00220	C-0152	2026-06-06	Q1	store	1370	delivered
KR-00221	C-0206	2026-04-07	Q1	app	3790	delivered
KR-00222	C-0173	2026-05-25	Q1	store	3410	delivered
KR-00223	C-0217	2026-06-16	Q1	web	2900	delivered
KR-00224	C-0213	2026-04-14	Q1	web	3850	delivered
KR-00225	C-0239	2026-05-17	Q1	app	3900	delivered
KR-00226	C-0248	2026-06-21	Q1	store	1380	delivered
KR-00227	C-0203	2026-04-16	Q1	app	1500	returned
KR-00228	C-0215	2026-05-10	Q1	store	4210	delivered
KR-00229	C-0164	2026-06-19	Q1	app	1370	delivered
KR-00230	C-0154	2026-04-13	Q1	store	3610	delivered
KR-00231	C-0174	2026-05-15	Q1	store	3980	delivered
KR-00232	C-0189	2026-06-13	Q1	app	1950	returned
KR-00233	C-0154	2026-04-08	Q1	app	2350	delivered
KR-00234	C-0190	2026-05-10	Q1	store	3580	cancelled
KR-00235	C-0166	2026-06-23	Q1	app	4320	delivered
KR-00236	C-0230	2026-04-05	Q1	web	2440	cancelled
KR-00237	C-0175	2026-05-26	Q1	store	2030	delivered
KR-00238	C-0222	2026-06-24	Q1	web	1890	delivered
KR-00239	C-0153	2026-04-25	Q1	store	4170	delivered
KR-00240	C-0182	2026-05-13	Q1	app	4120	delivered
KR-00241	C-0241	2026-06-03	Q1	store	2360	cancelled
KR-00242	C-0154	2026-04-04	Q1	web	1360	returned
KR-00243	C-0171	2026-05-26	Q1	store	1360	delivered
KR-00244	C-0223	2026-06-13	Q1	web	2860	returned
KR-00245	C-0185	2026-04-15	Q1	store	4430	delivered
KR-00246	C-0164	2026-05-06	Q1	store	1580	delivered
KR-00247	C-0163	2026-06-20	Q1	web	2410	delivered
KR-00248	C-0184	2026-04-28	Q1	store	2460	delivered
KR-00249	C-0180	2026-05-26	Q1	web	2580	cancelled
KR-00250	C-0151	2026-06-17	Q1	store	2940	delivered
KR-00251	C-0151	2026-04-14	Q1	web	3510	delivered
KR-00252	C-0162	2026-05-04	Q1	app	3250	cancelled
KR-00253	C-0166	2026-06-15	Q1	store	4240	returned
KR-00254	C-0158	2026-04-22	Q1	store	1360	delivered
KR-00255	C-0171	2026-05-25	Q1	web	3290	returned
KR-00256	C-0172	2026-06-04	Q1	app	4120	delivered
KR-00257	C-0159	2026-04-01	Q1	web	3980	cancelled
KR-00258	C-0165	2026-05-18	Q1	store	3750	delivered
KR-00259	C-0244	2026-06-05	Q1	web	1350	delivered
KR-00260	C-0167	2026-04-19	Q1	store	1810	returned
KR-00261	C-0168	2026-05-07	Q1	web	1660	delivered
KR-00262	C-0164	2026-06-11	Q1	app	1350	delivered
KR-00263	C-0163	2026-04-28	Q1	web	2750	delivered
KR-00264	C-0170	2026-05-08	Q1	web	2930	delivered
KR-00265	C-0158	2026-06-22	Q1	app	2760	delivered
KR-00266	C-0186	2026-04-16	Q1	app	3050	cancelled
KR-00267	C-0198	2026-05-17	Q1	web	3960	delivered
KR-00268	C-0249	2026-06-03	Q1	store	2980	delivered
KR-00269	C-0168	2026-04-11	Q1	store	1620	cancelled
KR-00270	C-0205	2026-05-04	Q1	web	3710	delivered
KR-00271	C-0161	2026-06-09	Q1	app	3520	cancelled
KR-00272	C-0197	2026-04-18	Q1	app	2460	delivered
KR-00273	C-0151	2026-05-22	Q1	app	1460	delivered
KR-00274	C-0152	2026-06-21	Q1	store	4440	delivered
KR-00275	C-0165	2026-04-18	Q1	store	4090	returned
KR-00276	C-0181	2026-05-22	Q1	app	1780	delivered
KR-00277	C-0166	2026-06-26	Q1	store	4010	delivered
KR-00278	C-0175	2026-04-28	Q1	app	2740	returned
KR-00279	C-0238	2026-05-14	Q1	app	2310	returned
KR-00280	C-0187	2026-06-23	Q1	store	3660	delivered
KR-00281	C-0198	2026-04-11	Q1	store	4300	cancelled
KR-00282	C-0186	2026-05-09	Q1	web	3020	cancelled
KR-00283	C-0164	2026-06-02	Q1	web	1560	delivered
KR-00284	C-0238	2026-04-26	Q1	web	2950	returned
KR-00285	C-0234	2026-05-21	Q1	store	3660	delivered
KR-00286	C-0173	2026-06-19	Q1	web	2560	returned
KR-00287	C-0205	2026-04-12	Q1	web	2140	returned
KR-00288	C-0170	2026-05-01	Q1	web	2500	returned
KR-00289	C-0179	2026-06-22	Q1	store	3460	returned
KR-00290	C-0155	2026-04-20	Q1	web	4010	delivered
KR-00291	C-0183	2026-05-07	Q1	store	1350	delivered
KR-00292	C-0167	2026-06-25	Q1	web	3300	delivered
KR-00293	C-0151	2026-04-27	Q1	app	3060	returned
KR-00294	C-0242	2026-05-13	Q1	web	1850	delivered
KR-00295	C-0181	2026-06-05	Q1	store	2990	delivered
KR-00296	C-0199	2026-04-23	Q1	store	2420	delivered
KR-00297	C-0208	2026-05-24	Q1	web	3530	returned
KR-00298	C-0230	2026-06-10	Q1	app	2250	cancelled
KR-00299	C-0228	2026-04-08	Q1	web	2150	returned
KR-00300	C-0245	2026-05-02	Q1	app	2630	delivered
KR-00301	C-0195	2026-06-09	Q1	web	3610	delivered
KR-00302	C-0224	2026-04-21	Q1	web	3280	delivered
KR-00303	C-0238	2026-05-07	Q1	app	1330	delivered
KR-00304	C-0157	2026-06-20	Q1	app	3660	delivered
KR-00305	C-0228	2026-04-18	Q1	app	2120	returned
KR-00306	C-0212	2026-05-12	Q1	store	3820	cancelled
KR-00307	C-0205	2026-06-06	Q1	web	1400	returned
KR-00308	C-0253	2026-04-17	Q1	web	2890	delivered
KR-00309	C-0204	2026-05-19	Q1	web	4270	returned
KR-00310	C-0212	2026-06-06	Q1	app	4450	cancelled
KR-00311	C-0205	2026-04-21	Q1	app	3780	delivered
KR-00312	C-0173	2026-05-03	Q1	web	2280	delivered
KR-00313	C-0192	2026-06-13	Q1	app	3650	delivered
KR-00314	C-0185	2026-04-04	Q1	store	3180	delivered
KR-00315	C-0265	2026-05-14	Q1	store	2170	delivered
KR-00316	C-0189	2026-06-13	Q1	store	3320	cancelled
KR-00317	C-0175	2026-04-20	Q1	app	3920	delivered
KR-00318	C-0160	2026-05-19	Q1	app	2190	delivered
KR-00319	C-0171	2026-06-03	Q1	store	4430	delivered
KR-00320	C-0235	2026-04-08	Q1	web	2640	delivered
KR-00321	C-0190	2026-05-15	Q1	store	1390	delivered
KR-00322	C-0183	2026-06-09	Q1	app	1940	returned
KR-00323	C-0202	2026-04-19	Q1	store	1450	delivered
KR-00324	C-0169	2026-05-15	Q1	app	2340	returned
KR-00325	C-0175	2026-06-06	Q1	app	3670	delivered
KR-00326	C-0204	2026-04-21	Q1	store	3580	delivered
KR-00327	C-0153	2026-05-17	Q1	app	2480	returned
KR-00328	C-0152	2026-06-27	Q1	web	1370	delivered
KR-00329	C-0177	2026-04-07	Q1	web	2430	delivered
KR-00330	C-0174	2026-05-04	Q1	web	1530	delivered
KR-00331	C-0256	2026-06-28	Q1	web	1270	cancelled
KR-00332	C-0211	2026-04-15	Q1	app	3530	returned
KR-00333	C-0239	2026-05-12	Q1	app	1680	delivered
KR-00334	C-0160	2026-06-09	Q1	web	4310	cancelled
KR-00335	C-0155	2026-04-28	Q1	store	3520	cancelled
KR-00336	C-0190	2026-05-16	Q1	store	3580	cancelled
KR-00337	C-0183	2026-06-28	Q1	app	1930	returned
KR-00338	C-0160	2026-04-14	Q1	app	4080	delivered
KR-00339	C-0187	2026-05-25	Q1	web	1360	delivered
KR-00340	C-0081	2026-04-19	Q1	web	1980	delivered
KR-00341	C-0112	2026-05-14	Q1	web	2030	delivered
KR-00342	C-0013	2026-06-22	Q1	web	2290	delivered
KR-00343	C-0036	2026-04-07	Q1	web	2900	cancelled
KR-00344	C-0013	2026-05-07	Q1	app	880	cancelled
KR-00345	C-0064	2026-06-24	Q1	app	2100	cancelled
KR-00346	C-0003	2026-04-03	Q1	app	1670	delivered
KR-00347	C-0040	2026-05-07	Q1	web	2420	delivered
KR-00348	C-0041	2026-06-27	Q1	web	1290	delivered
KR-00349	C-0097	2026-04-10	Q1	web	2050	delivered
KR-00350	C-0025	2026-05-16	Q1	store	2750	delivered
KR-00351	C-0086	2026-06-14	Q1	app	2570	delivered
KR-00352	C-0040	2026-04-14	Q1	web	2220	delivered
KR-00353	C-0122	2026-05-01	Q1	store	1570	delivered
KR-00354	C-0042	2026-06-26	Q1	app	2270	delivered
KR-00355	C-0002	2026-04-28	Q1	store	1240	delivered
KR-00356	C-0079	2026-05-16	Q1	store	1630	delivered
KR-00357	C-0012	2026-06-10	Q1	app	1900	returned
KR-00358	C-0025	2026-04-19	Q1	app	2080	returned
KR-00359	C-0095	2026-05-16	Q1	app	1060	delivered
KR-00360	C-0033	2026-06-11	Q1	app	1160	cancelled
KR-00361	C-0038	2026-04-18	Q1	app	2000	cancelled
KR-00362	C-0106	2026-05-07	Q1	store	840	cancelled
KR-00363	C-0093	2026-06-21	Q1	app	1520	delivered
KR-00364	C-0041	2026-04-10	Q1	web	1380	cancelled
KR-00365	C-0007	2026-05-03	Q1	store	950	cancelled
KR-00366	C-0122	2026-06-05	Q1	web	1870	delivered
KR-00367	C-0039	2026-04-21	Q1	web	2860	cancelled
KR-00368	C-0021	2026-05-02	Q1	store	2440	delivered
KR-00369	C-0142	2026-06-13	Q1	web	2150	delivered
KR-00370	C-0006	2026-04-20	Q1	app	2910	returned
KR-00371	C-0014	2026-05-08	Q1	app	2520	delivered
KR-00372	C-0132	2026-06-16	Q1	store	2850	returned
KR-00373	C-0035	2026-04-05	Q1	app	1950	delivered
KR-00374	C-0063	2026-05-14	Q1	store	1900	cancelled
KR-00375	C-0131	2026-06-06	Q1	web	2400	cancelled
KR-00376	C-0005	2026-04-20	Q1	web	1230	delivered
KR-00377	C-0109	2026-05-02	Q1	web	1400	delivered
KR-00378	C-0027	2026-06-14	Q1	store	2550	delivered
KR-00379	C-0087	2026-04-12	Q1	app	1540	cancelled
KR-00380	C-0051	2026-05-23	Q1	app	2240	delivered
KR-00381	C-0036	2026-06-14	Q1	store	1150	delivered
KR-00382	C-0030	2026-04-02	Q1	store	2220	delivered
KR-00383	C-0089	2026-05-18	Q1	store	1260	delivered
KR-00384	C-0085	2026-06-10	Q1	store	1860	delivered
KR-00385	C-0137	2026-04-02	Q1	app	2980	delivered
KR-00386	C-0034	2026-05-03	Q1	app	1920	cancelled
KR-00387	C-0105	2026-06-10	Q1	store	1780	delivered
KR-00388	C-0121	2026-04-01	Q1	app	1090	delivered
KR-00389	C-0026	2026-05-22	Q1	app	2550	returned
KR-00390	C-0055	2026-06-16	Q1	web	1700	delivered
KR-00391	C-0065	2026-04-17	Q1	app	980	delivered
KR-00392	C-0011	2026-05-23	Q1	app	1970	delivered
KR-00393	C-0080	2026-06-12	Q1	store	2960	delivered
KR-00394	C-0074	2026-04-26	Q1	app	2730	delivered
KR-00395	C-0038	2026-05-11	Q1	store	1360	cancelled
KR-00396	C-0018	2026-06-18	Q1	web	1990	delivered
KR-00397	C-0022	2026-04-23	Q1	app	1060	delivered
KR-00398	C-0038	2026-05-13	Q1	web	2200	delivered
KR-00399	C-0145	2026-06-10	Q1	app	2500	delivered
KR-00400	C-0091	2026-04-25	Q1	store	2080	delivered
KR-00401	C-0030	2026-05-21	Q1	web	1490	delivered
KR-00402	C-0039	2026-06-14	Q1	store	2100	delivered
KR-00403	C-0035	2026-04-26	Q1	app	2550	cancelled
KR-00404	C-0093	2026-05-17	Q1	store	1820	delivered
KR-00405	C-0050	2026-06-18	Q1	store	2650	delivered
KR-00406	C-0134	2026-04-12	Q1	web	1870	delivered
KR-00407	C-0026	2026-05-01	Q1	store	950	returned
KR-00408	C-0135	2026-06-06	Q1	app	1440	delivered
KR-00409	C-0029	2026-04-02	Q1	app	1110	delivered
KR-00410	C-0032	2026-05-08	Q1	web	2610	delivered
KR-00411	C-0032	2026-06-13	Q1	app	2250	delivered
KR-00412	C-0069	2026-04-17	Q1	web	2490	delivered
KR-00413	C-0011	2026-05-09	Q1	app	2540	delivered
KR-00414	C-0038	2026-06-06	Q1	store	1450	delivered
KR-00415	C-0088	2026-04-08	Q1	app	870	delivered
KR-00416	C-0029	2026-05-02	Q1	web	870	returned
KR-00417	C-0135	2026-06-09	Q1	store	2850	delivered
KR-00418	C-0044	2026-04-07	Q1	web	1370	delivered
KR-00419	C-0008	2026-05-14	Q1	app	1740	delivered
KR-00420	C-0064	2026-06-21	Q1	store	1840	delivered
KR-00421	C-0021	2026-04-14	Q1	web	2500	delivered
KR-00422	C-0071	2026-05-12	Q1	app	2520	delivered
KR-00423	C-0038	2026-06-11	Q1	app	1530	returned
KR-00424	C-0023	2026-04-12	Q1	web	2390	delivered
KR-00425	C-0032	2026-05-04	Q1	web	1340	delivered
KR-00426	C-0050	2026-06-26	Q1	app	1970	delivered
KR-00427	C-0046	2026-04-17	Q1	app	1490	delivered
KR-00428	C-0141	2026-05-05	Q1	app	2140	delivered
KR-00429	C-0036	2026-06-15	Q1	store	1170	delivered
KR-00430	C-0003	2026-04-27	Q1	web	2720	delivered
KR-00431	C-0048	2026-05-12	Q1	web	1640	delivered
KR-00432	C-0097	2026-06-10	Q1	web	890	delivered
KR-00433	C-0083	2026-04-20	Q1	store	1460	delivered
KR-00434	C-0016	2026-05-01	Q1	app	2120	cancelled
KR-00435	C-0083	2026-06-18	Q1	app	1860	delivered
KR-00436	C-0038	2026-04-15	Q1	store	940	delivered
KR-00437	C-0050	2026-05-22	Q1	app	2940	delivered
KR-00438	C-0030	2026-06-24	Q1	web	1780	delivered
KR-00439	C-0001	2026-04-04	Q1	store	2430	delivered
KR-00440	C-0038	2026-05-11	Q1	app	2360	returned
KR-00441	C-0023	2026-06-19	Q1	web	2980	returned
KR-00442	C-0119	2026-04-15	Q1	store	1810	delivered
KR-00443	C-0055	2026-05-28	Q1	app	1940	delivered
KR-00444	C-0145	2026-06-25	Q1	app	910	delivered
KR-00445	C-0018	2026-04-08	Q1	store	1810	delivered
KR-00446	C-0025	2026-05-23	Q1	app	1060	delivered
KR-00447	C-0031	2026-06-11	Q1	store	2590	delivered
KR-00448	C-0042	2026-04-27	Q1	store	2530	delivered
KR-00449	C-0080	2026-05-01	Q1	app	2250	delivered
KR-00450	C-0150	2026-06-04	Q1	store	1370	returned
KR-00451	C-0014	2026-04-27	Q1	store	1590	delivered
KR-00452	C-0038	2026-05-08	Q1	app	2470	delivered
KR-00453	C-0111	2026-06-17	Q1	store	2650	delivered
KR-00454	C-0017	2026-04-05	Q1	store	1310	delivered
KR-00455	C-0042	2026-05-10	Q1	store	1270	delivered
KR-00456	C-0113	2026-06-23	Q1	web	2490	delivered
KR-00457	C-0030	2026-04-16	Q1	web	2440	delivered
KR-00458	C-0125	2026-05-02	Q1	app	1800	returned
KR-00459	C-0037	2026-06-24	Q1	web	2680	delivered
KR-00460	C-0014	2026-04-11	Q1	store	2480	delivered
KR-00461	C-0056	2026-05-27	Q1	web	1120	returned
KR-00462	C-0023	2026-06-23	Q1	web	2170	cancelled
KR-00463	C-0070	2026-04-08	Q1	app	1630	delivered
KR-00464	C-0024	2026-05-27	Q1	web	2930	delivered
KR-00465	C-0055	2026-06-03	Q1	store	2560	cancelled
KR-00466	C-0002	2026-04-07	Q1	app	1460	delivered
KR-00467	C-0085	2026-05-27	Q1	app	1210	delivered
KR-00468	C-0050	2026-06-18	Q1	store	960	returned
KR-00469	C-0101	2026-04-27	Q1	store	1590	delivered
KR-00470	C-0002	2026-05-03	Q1	store	1600	delivered
KR-00471	C-0017	2026-06-04	Q1	store	2930	delivered
KR-00472	C-0124	2026-04-16	Q1	app	2480	delivered
KR-00473	C-0026	2026-05-11	Q1	store	2030	delivered
KR-00474	C-0021	2026-06-22	Q1	app	2670	cancelled
KR-00475	C-0143	2026-04-03	Q1	app	980	cancelled
KR-00476	C-0129	2026-05-02	Q1	web	970	delivered
KR-00477	C-0032	2026-06-18	Q1	app	1960	delivered
KR-00478	C-0032	2026-04-13	Q1	store	1560	cancelled
KR-00479	C-0042	2026-05-07	Q1	store	1890	cancelled
KR-00480	C-0066	2026-06-18	Q1	store	1970	delivered
KR-00481	C-0049	2026-04-24	Q1	web	1270	cancelled
KR-00482	C-0060	2026-05-15	Q1	app	1890	delivered
KR-00483	C-0014	2026-06-20	Q1	store	2430	delivered
KR-00484	C-0008	2026-04-22	Q1	app	1150	delivered
KR-00485	C-0082	2026-05-14	Q1	app	1460	delivered
KR-00486	C-0020	2026-06-03	Q1	app	1040	cancelled
KR-00487	C-0044	2026-04-11	Q1	web	2030	delivered
KR-00488	C-0006	2026-05-12	Q1	store	2990	delivered
KR-00489	C-0026	2026-06-13	Q1	web	2530	delivered
KR-00490	C-0016	2026-04-28	Q1	app	1210	delivered
KR-00491	C-0028	2026-05-28	Q1	store	1450	delivered
KR-00492	C-0013	2026-06-21	Q1	app	2770	delivered
KR-00493	C-0050	2026-04-19	Q1	web	2530	delivered
KR-00494	C-0047	2026-05-17	Q1	app	2200	delivered
KR-00495	C-0008	2026-06-23	Q1	app	1340	delivered
KR-00496	C-0089	2026-04-08	Q1	web	1690	cancelled
KR-00497	C-0110	2026-05-01	Q1	store	2720	delivered
KR-00498	C-0085	2026-06-09	Q1	store	2440	delivered
KR-00499	C-0010	2026-04-02	Q1	store	2720	cancelled
KR-00500	C-0050	2026-05-12	Q1	store	1140	delivered
KR-00501	C-0129	2026-06-17	Q1	store	1130	delivered
KR-00502	C-0077	2026-04-12	Q1	web	2960	delivered
KR-00503	C-0104	2026-05-24	Q1	web	1780	delivered
KR-00504	C-0079	2026-06-23	Q1	web	2690	returned
KR-00505	C-0085	2026-04-15	Q1	app	1410	delivered
KR-00506	C-0129	2026-05-04	Q1	app	1960	delivered
KR-00507	C-0149	2026-06-22	Q1	store	1350	cancelled
KR-00508	C-0046	2026-04-17	Q1	app	1110	delivered
KR-00509	C-0022	2026-05-07	Q1	app	1240	delivered
KR-00510	C-0131	2026-06-25	Q1	store	2290	delivered
KR-00511	C-0108	2026-04-27	Q1	store	2650	returned
KR-00512	C-0122	2026-05-23	Q1	app	1130	returned
KR-00513	C-0027	2026-06-20	Q1	web	1020	delivered
KR-00514	C-0005	2026-04-12	Q1	store	1800	cancelled
KR-00515	C-0081	2026-05-01	Q1	app	1580	delivered
KR-00516	C-0136	2026-06-13	Q1	web	1940	delivered
KR-00517	C-0019	2026-04-13	Q1	app	820	delivered
KR-00518	C-0014	2026-05-14	Q1	app	2410	returned
KR-00519	C-0046	2026-06-21	Q1	web	1850	cancelled
KR-00520	C-0092	2026-04-24	Q1	app	1630	returned
KR-00521	C-0132	2026-05-21	Q1	web	1030	delivered
KR-00522	C-0030	2026-06-18	Q1	web	1760	delivered
KR-00523	C-0109	2026-04-02	Q1	app	1760	delivered
KR-00524	C-0003	2026-05-08	Q1	app	2150	delivered
KR-00525	C-0040	2026-06-01	Q1	web	1490	delivered
KR-00526	C-0075	2026-04-26	Q1	store	2860	returned
KR-00527	C-0036	2026-05-13	Q1	store	1520	cancelled
KR-00528	C-0023	2026-06-22	Q1	web	1570	returned
KR-00529	C-0067	2026-04-21	Q1	app	2270	delivered
KR-00530	C-0032	2026-05-12	Q1	web	940	delivered
KR-00531	C-0074	2026-06-08	Q1	app	1890	delivered
KR-00532	C-0148	2026-04-04	Q1	app	2280	returned
KR-00533	C-0092	2026-05-04	Q1	store	2930	cancelled
KR-00534	C-0105	2026-06-26	Q1	app	1190	cancelled
KR-00535	C-0038	2026-04-05	Q1	web	2230	cancelled
KR-00536	C-0006	2026-05-21	Q1	store	1200	cancelled
KR-00537	C-0126	2026-06-25	Q1	web	980	delivered
KR-00538	C-0008	2026-04-13	Q1	app	2740	delivered
KR-00539	C-0319	2026-07-07	Q2	app	1460	delivered
KR-00540	C-0320	2026-08-28	Q2	web	1150	delivered
KR-00541	C-0328	2026-09-06	Q2	app	1010	returned
KR-00542	C-0334	2026-07-28	Q2	store	580	delivered
KR-00543	C-0312	2026-08-18	Q2	app	1270	delivered
KR-00544	C-0324	2026-09-13	Q2	store	600	delivered
KR-00545	C-0313	2026-07-08	Q2	web	1400	delivered
KR-00546	C-0320	2026-08-20	Q2	app	800	delivered
KR-00547	C-0312	2026-09-18	Q2	app	1030	cancelled
KR-00548	C-0340	2026-07-23	Q2	web	1080	delivered
KR-00549	C-0320	2026-08-15	Q2	app	520	returned
KR-00550	C-0318	2026-09-15	Q2	store	460	returned
KR-00551	C-0313	2026-07-26	Q2	web	1310	delivered
KR-00552	C-0312	2026-08-02	Q2	app	1120	delivered
KR-00553	C-0322	2026-09-18	Q2	web	980	returned
KR-00554	C-0330	2026-07-05	Q2	web	1280	delivered
KR-00555	C-0320	2026-08-24	Q2	app	1330	returned
KR-00556	C-0330	2026-09-19	Q2	store	1180	delivered
KR-00557	C-0326	2026-07-22	Q2	app	1340	delivered
KR-00558	C-0315	2026-08-14	Q2	store	1160	delivered
KR-00559	C-0315	2026-09-11	Q2	store	810	delivered
KR-00560	C-0320	2026-07-23	Q2	app	840	delivered
KR-00561	C-0329	2026-08-25	Q2	app	910	delivered
KR-00562	C-0317	2026-09-26	Q2	app	600	delivered
KR-00563	C-0328	2026-07-26	Q2	store	640	returned
KR-00564	C-0312	2026-08-18	Q2	web	830	cancelled
KR-00565	C-0335	2026-09-16	Q2	store	620	delivered
KR-00566	C-0320	2026-07-11	Q2	app	470	delivered
KR-00567	C-0313	2026-08-08	Q2	store	640	returned
KR-00568	C-0311	2026-09-07	Q2	store	550	delivered
KR-00569	C-0333	2026-07-23	Q2	app	880	delivered
KR-00570	C-0316	2026-08-23	Q2	store	1120	delivered
KR-00571	C-0318	2026-09-13	Q2	app	440	delivered
KR-00572	C-0330	2026-07-18	Q2	app	450	returned
KR-00573	C-0318	2026-08-05	Q2	web	1230	cancelled
KR-00574	C-0313	2026-09-20	Q2	store	920	cancelled
KR-00575	C-0338	2026-07-20	Q2	store	840	delivered
KR-00576	C-0335	2026-08-02	Q2	store	510	delivered
KR-00577	C-0291	2026-07-08	Q2	app	240000	delivered
KR-00578	C-0291	2026-08-09	Q2	web	1750000	delivered
KR-00579	C-0309	2026-09-10	Q2	app	397000	delivered
KR-00580	C-0273	2026-07-26	Q2	app	1673000	delivered
KR-00581	C-0290	2026-08-20	Q2	store	1359000	delivered
KR-00582	C-0282	2026-09-14	Q2	app	1262000	delivered
KR-00583	C-0286	2026-07-08	Q2	web	1286000	delivered
KR-00584	C-0303	2026-08-19	Q2	store	1097000	returned
KR-00585	C-0298	2026-09-04	Q2	web	918000	delivered
KR-00586	C-0281	2026-07-02	Q2	web	529000	delivered
KR-00587	C-0281	2026-08-27	Q2	app	458000	delivered
KR-00588	C-0282	2026-09-06	Q2	web	1706000	returned
KR-00589	C-0294	2026-07-12	Q2	store	1346000	delivered
KR-00590	C-0282	2026-08-10	Q2	web	276000	delivered
KR-00591	C-0287	2026-09-22	Q2	app	1681000	delivered
KR-00592	C-0303	2026-07-18	Q2	app	952000	cancelled
KR-00593	C-0271	2026-08-20	Q2	app	1359000	cancelled
KR-00594	C-0302	2026-09-09	Q2	store	899000	delivered
KR-00595	C-0308	2026-07-08	Q2	web	468000	returned
KR-00596	C-0274	2026-08-23	Q2	app	1251000	delivered
KR-00597	C-0295	2026-09-02	Q2	app	1422000	delivered
KR-00598	C-0279	2026-07-18	Q2	web	888000	delivered
KR-00599	C-0290	2026-08-28	Q2	store	1179000	returned
KR-00600	C-0282	2026-09-16	Q2	app	324000	delivered
KR-00601	C-0271	2026-07-27	Q2	app	388000	delivered
KR-00602	C-0279	2026-08-17	Q2	web	390000	cancelled
KR-00603	C-0300	2026-09-10	Q2	store	239000	cancelled
KR-00604	C-0272	2026-07-24	Q2	web	982000	delivered
KR-00605	C-0284	2026-08-27	Q2	app	1219000	delivered
KR-00606	C-0278	2026-09-13	Q2	store	1276000	delivered
KR-00607	C-0281	2026-07-23	Q2	store	1665000	delivered
KR-00608	C-0305	2026-08-09	Q2	store	980000	delivered
KR-00609	C-0271	2026-09-03	Q2	app	310000	delivered
KR-00610	C-0292	2026-07-01	Q2	web	1477000	returned
KR-00611	C-0288	2026-08-03	Q2	app	249000	delivered
KR-00612	C-0275	2026-09-26	Q2	app	1667000	delivered
KR-00613	C-0280	2026-07-15	Q2	app	678000	cancelled
KR-00614	C-0285	2026-08-22	Q2	app	213000	delivered
KR-00615	C-0272	2026-09-13	Q2	app	897000	delivered
KR-00616	C-0302	2026-07-05	Q2	store	546000	cancelled
KR-00617	C-0279	2026-08-15	Q2	web	1165000	delivered
KR-00618	C-0273	2026-09-07	Q2	store	946000	delivered
KR-00619	C-0278	2026-07-04	Q2	app	469000	delivered
KR-00620	C-0290	2026-08-28	Q2	store	1006000	cancelled
KR-00621	C-0295	2026-09-18	Q2	store	1545000	delivered
KR-00622	C-0277	2026-07-16	Q2	web	1672000	delivered
KR-00623	C-0291	2026-08-02	Q2	app	664000	cancelled
KR-00624	C-0280	2026-09-18	Q2	web	783000	delivered
KR-00625	C-0291	2026-07-10	Q2	web	1100000	cancelled
KR-00626	C-0287	2026-08-06	Q2	web	876000	delivered
KR-00627	C-0285	2026-09-25	Q2	web	1229000	returned
KR-00628	C-0275	2026-07-08	Q2	store	901000	delivered
KR-00629	C-0272	2026-08-04	Q2	web	310000	returned
KR-00630	C-0284	2026-09-08	Q2	app	1461000	cancelled
KR-00631	C-0274	2026-07-13	Q2	web	1140000	delivered
KR-00632	C-0296	2026-08-21	Q2	web	1624000	delivered
KR-00633	C-0278	2026-09-15	Q2	web	230000	delivered
KR-00634	C-0279	2026-07-21	Q2	app	968000	delivered
KR-00635	C-0310	2026-08-16	Q2	web	338000	delivered
KR-00636	C-0273	2026-09-25	Q2	app	1000000	delivered
KR-00637	C-0271	2026-07-28	Q2	app	1401000	delivered
KR-00638	C-0280	2026-08-24	Q2	app	937000	cancelled
KR-00639	C-0282	2026-09-06	Q2	store	1139000	delivered
KR-00640	C-0280	2026-07-24	Q2	web	1661000	delivered
KR-00641	C-0273	2026-08-01	Q2	store	859000	delivered
KR-00642	C-0276	2026-09-15	Q2	store	317000	returned
KR-00643	C-0288	2026-07-14	Q2	store	1256000	delivered
KR-00644	C-0279	2026-08-18	Q2	app	1755000	delivered
KR-00645	C-0298	2026-09-01	Q2	app	797000	delivered
KR-00646	C-0303	2026-07-04	Q2	store	1450000	delivered
KR-00647	C-0296	2026-08-16	Q2	store	1378000	delivered
KR-00648	C-0271	2026-09-17	Q2	store	876000	delivered
KR-00649	C-0278	2026-07-05	Q2	store	216000	delivered
KR-00650	C-0276	2026-08-24	Q2	store	1017000	cancelled
KR-00651	C-0304	2026-09-03	Q2	app	855000	delivered
KR-00652	C-0307	2026-07-08	Q2	store	1231000	cancelled
KR-00653	C-0290	2026-08-27	Q2	web	888000	returned
KR-00654	C-0276	2026-09-03	Q2	app	1244000	delivered
KR-00655	C-0303	2026-07-26	Q2	web	1014000	delivered
KR-00656	C-0277	2026-08-19	Q2	app	326000	delivered
KR-00657	C-0286	2026-09-02	Q2	web	1246000	delivered
KR-00658	C-0271	2026-07-08	Q2	web	1175000	delivered
KR-00659	C-0279	2026-08-01	Q2	app	1667000	delivered
KR-00660	C-0295	2026-09-18	Q2	web	1580000	returned
KR-00661	C-0281	2026-07-03	Q2	store	1002000	delivered
KR-00662	C-0308	2026-08-10	Q2	app	678000	delivered
KR-00663	C-0295	2026-09-27	Q2	app	6296590	delivered
KR-00664	C-0154	2026-07-12	Q2	web	4200	delivered
KR-00665	C-0154	2026-08-13	Q2	web	3100	delivered
KR-00666	C-0154	2026-09-14	Q2	app	1900	delivered
KR-00667	C-0165	2026-07-12	Q2	web	3800	cancelled
KR-00668	C-0165	2026-08-13	Q2	app	2600	delivered
KR-00669	C-0165	2026-09-14	Q2	app	1400	delivered
KR-00670	C-0170	2026-07-12	Q2	store	4400	delivered
KR-00671	C-0170	2026-08-13	Q2	web	2900	delivered
KR-00672	C-0170	2026-09-14	Q2	web	1600	delivered
KR-00673	C-0261	2026-07-16	Q2	store	2990	cancelled
KR-00674	C-0198	2026-08-10	Q2	web	3830	returned
KR-00675	C-0245	2026-09-17	Q2	web	2490	delivered
KR-00676	C-0175	2026-07-21	Q2	store	2100	delivered
KR-00677	C-0242	2026-08-16	Q2	store	2230	returned
KR-00678	C-0257	2026-09-18	Q2	store	3900	delivered
KR-00679	C-0161	2026-07-04	Q2	web	1950	delivered
KR-00680	C-0186	2026-08-10	Q2	web	3370	returned
KR-00681	C-0166	2026-09-01	Q2	store	2840	delivered
KR-00682	C-0182	2026-07-09	Q2	app	3620	delivered
KR-00683	C-0166	2026-08-07	Q2	web	1630	delivered
KR-00684	C-0182	2026-09-20	Q2	store	1870	delivered
KR-00685	C-0199	2026-07-01	Q2	web	1320	cancelled
KR-00686	C-0226	2026-08-24	Q2	app	1630	delivered
KR-00687	C-0183	2026-09-19	Q2	web	3610	returned
KR-00688	C-0207	2026-07-08	Q2	web	1390	returned
KR-00689	C-0153	2026-08-09	Q2	web	3250	delivered
KR-00690	C-0168	2026-09-20	Q2	app	3770	delivered
KR-00691	C-0260	2026-07-07	Q2	web	1910	returned
KR-00692	C-0183	2026-08-05	Q2	store	4350	returned
KR-00693	C-0176	2026-09-04	Q2	web	1580	cancelled
KR-00694	C-0213	2026-07-14	Q2	web	2920	returned
KR-00695	C-0190	2026-08-25	Q2	web	4430	cancelled
KR-00696	C-0153	2026-09-12	Q2	web	3460	returned
KR-00697	C-0224	2026-07-17	Q2	web	1930	delivered
KR-00698	C-0226	2026-08-24	Q2	app	1760	delivered
KR-00699	C-0232	2026-09-24	Q2	store	4500	delivered
KR-00700	C-0219	2026-07-05	Q2	app	4330	delivered
KR-00701	C-0159	2026-08-03	Q2	store	1330	returned
KR-00702	C-0163	2026-09-28	Q2	app	1450	delivered
KR-00703	C-0174	2026-07-18	Q2	store	2540	delivered
KR-00704	C-0206	2026-08-11	Q2	store	4140	returned
KR-00705	C-0246	2026-09-21	Q2	store	2530	cancelled
KR-00706	C-0184	2026-07-02	Q2	app	4210	delivered
KR-00707	C-0240	2026-08-12	Q2	store	1370	cancelled
KR-00708	C-0162	2026-09-23	Q2	app	3310	returned
KR-00709	C-0184	2026-07-12	Q2	store	1210	delivered
KR-00710	C-0204	2026-08-26	Q2	app	1490	returned
KR-00711	C-0157	2026-09-26	Q2	web	1630	delivered
KR-00712	C-0159	2026-07-12	Q2	web	2590	delivered
KR-00713	C-0163	2026-08-15	Q2	app	3480	delivered
KR-00714	C-0177	2026-09-07	Q2	web	4500	delivered
KR-00715	C-0268	2026-07-06	Q2	app	1900	delivered
KR-00716	C-0244	2026-08-17	Q2	web	1200	delivered
KR-00717	C-0188	2026-09-28	Q2	store	3220	delivered
KR-00718	C-0225	2026-07-06	Q2	store	2440	delivered
KR-00719	C-0190	2026-08-10	Q2	web	3230	delivered
KR-00720	C-0188	2026-09-25	Q2	store	1470	delivered
KR-00721	C-0209	2026-07-07	Q2	app	4420	delivered
KR-00722	C-0164	2026-08-20	Q2	app	4140	delivered
KR-00723	C-0252	2026-09-16	Q2	web	1960	cancelled
KR-00724	C-0161	2026-07-01	Q2	store	1950	cancelled
KR-00725	C-0197	2026-08-25	Q2	web	1370	delivered
KR-00726	C-0157	2026-09-08	Q2	store	2970	delivered
KR-00727	C-0263	2026-07-16	Q2	store	2080	delivered
KR-00728	C-0151	2026-08-21	Q2	store	2520	delivered
KR-00729	C-0221	2026-09-19	Q2	web	3000	returned
KR-00730	C-0265	2026-07-06	Q2	web	1840	returned
KR-00731	C-0203	2026-08-21	Q2	store	3780	delivered
KR-00732	C-0167	2026-09-25	Q2	app	1710	delivered
KR-00733	C-0213	2026-07-24	Q2	app	3800	delivered
KR-00734	C-0255	2026-08-27	Q2	web	1740	delivered
KR-00735	C-0234	2026-09-14	Q2	web	1990	returned
KR-00736	C-0184	2026-07-17	Q2	store	4390	cancelled
KR-00737	C-0207	2026-08-27	Q2	store	4010	delivered
KR-00738	C-0218	2026-09-20	Q2	store	2380	delivered
KR-00739	C-0162	2026-07-16	Q2	app	2870	cancelled
KR-00740	C-0161	2026-08-26	Q2	store	2970	returned
KR-00741	C-0268	2026-09-08	Q2	web	3740	delivered
KR-00742	C-0180	2026-07-28	Q2	store	1480	delivered
KR-00743	C-0221	2026-08-06	Q2	web	4090	delivered
KR-00744	C-0183	2026-09-22	Q2	store	1520	delivered
KR-00745	C-0235	2026-07-06	Q2	web	2330	delivered
KR-00746	C-0218	2026-08-25	Q2	store	4230	delivered
KR-00747	C-0159	2026-09-11	Q2	app	3060	delivered
KR-00748	C-0209	2026-07-10	Q2	web	2130	cancelled
KR-00749	C-0155	2026-08-24	Q2	store	4410	delivered
KR-00750	C-0200	2026-09-07	Q2	app	3090	returned
KR-00751	C-0162	2026-07-06	Q2	web	1760	delivered
KR-00752	C-0226	2026-08-22	Q2	app	2120	cancelled
KR-00753	C-0240	2026-09-02	Q2	app	1670	cancelled
KR-00754	C-0198	2026-07-14	Q2	app	3630	cancelled
KR-00755	C-0196	2026-08-24	Q2	store	4040	cancelled
KR-00756	C-0173	2026-09-03	Q2	app	1800	delivered
KR-00757	C-0156	2026-07-06	Q2	store	3540	delivered
KR-00758	C-0172	2026-08-28	Q2	app	2370	delivered
KR-00759	C-0259	2026-09-17	Q2	web	3020	delivered
KR-00760	C-0201	2026-07-23	Q2	store	4140	delivered
KR-00761	C-0192	2026-08-05	Q2	app	4380	delivered
KR-00762	C-0258	2026-09-28	Q2	store	3090	cancelled
KR-00763	C-0156	2026-07-03	Q2	app	3850	delivered
KR-00764	C-0267	2026-08-18	Q2	app	1570	delivered
KR-00765	C-0157	2026-09-17	Q2	store	2280	delivered
KR-00766	C-0168	2026-07-12	Q2	app	1720	delivered
KR-00767	C-0160	2026-08-13	Q2	app	4380	delivered
KR-00768	C-0158	2026-09-04	Q2	store	4160	delivered
KR-00769	C-0185	2026-07-21	Q2	store	3330	returned
KR-00770	C-0264	2026-08-06	Q2	store	4490	delivered
KR-00771	C-0223	2026-09-14	Q2	app	1360	delivered
KR-00772	C-0174	2026-07-04	Q2	web	2990	delivered
KR-00773	C-0247	2026-08-11	Q2	store	3680	delivered
KR-00774	C-0239	2026-09-14	Q2	store	3820	cancelled
KR-00775	C-0169	2026-07-21	Q2	app	3360	cancelled
KR-00776	C-0164	2026-08-04	Q2	store	3430	delivered
KR-00777	C-0189	2026-09-28	Q2	app	2010	delivered
KR-00778	C-0241	2026-07-11	Q2	web	3080	delivered
KR-00779	C-0269	2026-08-25	Q2	app	3390	delivered
KR-00780	C-0254	2026-09-13	Q2	app	3110	delivered
KR-00781	C-0233	2026-07-17	Q2	app	1640	delivered
KR-00782	C-0181	2026-08-18	Q2	app	2810	cancelled
KR-00783	C-0169	2026-09-15	Q2	store	3290	delivered
KR-00784	C-0173	2026-07-17	Q2	web	2830	delivered
KR-00785	C-0152	2026-08-18	Q2	app	3420	returned
KR-00786	C-0188	2026-09-07	Q2	store	1400	delivered
KR-00787	C-0243	2026-07-17	Q2	store	1560	cancelled
KR-00788	C-0151	2026-08-02	Q2	store	3310	returned
KR-00789	C-0155	2026-09-15	Q2	store	2570	cancelled
KR-00790	C-0230	2026-07-16	Q2	store	1340	cancelled
KR-00791	C-0163	2026-08-28	Q2	store	4090	delivered
KR-00792	C-0172	2026-09-01	Q2	store	1480	cancelled
KR-00793	C-0207	2026-07-19	Q2	store	1640	returned
KR-00794	C-0253	2026-08-13	Q2	app	2400	delivered
KR-00795	C-0157	2026-09-27	Q2	store	4240	cancelled
KR-00796	C-0186	2026-07-04	Q2	app	2610	returned
KR-00797	C-0184	2026-08-01	Q2	web	2820	delivered
KR-00798	C-0189	2026-09-23	Q2	app	2830	delivered
KR-00799	C-0178	2026-07-07	Q2	store	4350	delivered
KR-00800	C-0156	2026-08-23	Q2	web	3110	delivered
KR-00801	C-0175	2026-09-04	Q2	store	1580	delivered
KR-00802	C-0218	2026-07-25	Q2	app	4190	delivered
KR-00803	C-0253	2026-08-04	Q2	store	2550	delivered
KR-00804	C-0149	2026-07-13	Q2	web	1890	delivered
KR-00805	C-0052	2026-08-21	Q2	store	1220	cancelled
KR-00806	C-0075	2026-09-06	Q2	app	1550	returned
KR-00807	C-0040	2026-07-06	Q2	app	2740	returned
KR-00808	C-0013	2026-08-18	Q2	store	1550	returned
KR-00809	C-0058	2026-09-08	Q2	store	1420	delivered
KR-00810	C-0089	2026-07-04	Q2	store	1150	delivered
KR-00811	C-0096	2026-08-20	Q2	web	1700	delivered
KR-00812	C-0032	2026-09-07	Q2	web	1730	cancelled
KR-00813	C-0125	2026-07-02	Q2	web	2650	delivered
KR-00814	C-0011	2026-08-28	Q2	app	2750	delivered
KR-00815	C-0038	2026-09-13	Q2	app	2050	cancelled
KR-00816	C-0103	2026-07-22	Q2	store	1390	delivered
KR-00817	C-0057	2026-08-05	Q2	web	2940	delivered
KR-00818	C-0064	2026-09-23	Q2	web	2350	delivered
KR-00819	C-0087	2026-07-15	Q2	web	1700	delivered
KR-00820	C-0019	2026-08-14	Q2	app	1950	delivered
KR-00821	C-0082	2026-09-07	Q2	store	2770	delivered
KR-00822	C-0082	2026-07-20	Q2	web	1060	returned
KR-00823	C-0013	2026-08-06	Q2	web	2900	delivered
KR-00824	C-0004	2026-09-15	Q2	store	2820	cancelled
KR-00825	C-0044	2026-07-01	Q2	app	1420	delivered
KR-00826	C-0033	2026-08-13	Q2	app	930	returned
KR-00827	C-0011	2026-09-27	Q2	store	2870	delivered
KR-00828	C-0022	2026-07-07	Q2	web	980	delivered
KR-00829	C-0099	2026-08-13	Q2	store	1420	delivered
KR-00830	C-0072	2026-09-05	Q2	web	2090	delivered
KR-00831	C-0111	2026-07-15	Q2	app	980	delivered
KR-00832	C-0089	2026-08-03	Q2	app	960	cancelled
KR-00833	C-0082	2026-09-05	Q2	web	2270	returned
KR-00834	C-0077	2026-07-05	Q2	web	1230	returned
KR-00835	C-0029	2026-08-11	Q2	app	2340	returned
KR-00836	C-0050	2026-09-16	Q2	app	2200	delivered
KR-00837	C-0131	2026-07-21	Q2	app	1040	returned
KR-00838	C-0001	2026-08-12	Q2	web	1560	delivered
KR-00839	C-0115	2026-09-27	Q2	app	2870	returned
KR-00840	C-0039	2026-07-10	Q2	web	2370	delivered
KR-00841	C-0001	2026-08-13	Q2	web	2310	returned
KR-00842	C-0051	2026-09-12	Q2	app	2380	cancelled
KR-00843	C-0046	2026-07-13	Q2	web	890	delivered
KR-00844	C-0120	2026-08-25	Q2	app	1830	delivered
KR-00845	C-0097	2026-09-15	Q2	web	970	delivered
KR-00846	C-0098	2026-07-25	Q2	web	2080	delivered
KR-00847	C-0017	2026-08-09	Q2	web	1290	returned
KR-00848	C-0010	2026-09-21	Q2	web	1150	returned
KR-00849	C-0140	2026-07-15	Q2	web	2880	returned
KR-00850	C-0029	2026-08-26	Q2	app	2260	delivered
KR-00851	C-0062	2026-09-06	Q2	web	1350	delivered
KR-00852	C-0145	2026-07-23	Q2	app	1270	delivered
KR-00853	C-0104	2026-08-20	Q2	app	1830	delivered
KR-00854	C-0062	2026-09-21	Q2	web	1300	returned
KR-00855	C-0017	2026-07-08	Q2	web	1630	returned
KR-00856	C-0014	2026-08-06	Q2	app	1040	delivered
KR-00857	C-0048	2026-09-07	Q2	web	980	returned
KR-00858	C-0045	2026-07-10	Q2	store	1950	cancelled
KR-00859	C-0007	2026-08-16	Q2	store	2420	delivered
KR-00860	C-0026	2026-09-14	Q2	web	2480	cancelled
KR-00861	C-0091	2026-07-18	Q2	web	2400	cancelled
KR-00862	C-0033	2026-08-21	Q2	store	1330	delivered
KR-00863	C-0099	2026-09-05	Q2	web	1270	cancelled
KR-00864	C-0045	2026-07-13	Q2	web	1430	delivered
KR-00865	C-0004	2026-08-27	Q2	store	870	returned
KR-00866	C-0082	2026-09-28	Q2	app	2080	delivered
KR-00867	C-0024	2026-07-17	Q2	store	820	delivered
KR-00868	C-0049	2026-08-26	Q2	web	2040	delivered
KR-00869	C-0089	2026-09-08	Q2	store	1730	delivered
KR-00870	C-0097	2026-07-14	Q2	web	1130	cancelled
KR-00871	C-0086	2026-08-12	Q2	web	1740	delivered
KR-00872	C-0003	2026-09-24	Q2	store	2350	delivered
KR-00873	C-0017	2026-07-12	Q2	web	2250	delivered
KR-00874	C-0024	2026-08-28	Q2	store	2600	returned
KR-00875	C-0140	2026-09-05	Q2	web	1450	delivered
KR-00876	C-0054	2026-07-14	Q2	store	2680	cancelled
KR-00877	C-0100	2026-08-02	Q2	app	1120	delivered
KR-00878	C-0019	2026-09-06	Q2	web	990	delivered
KR-00879	C-0055	2026-07-17	Q2	store	2250	delivered
KR-00880	C-0126	2026-08-12	Q2	web	2980	delivered
KR-00881	C-0036	2026-09-25	Q2	app	960	delivered
KR-00882	C-0006	2026-07-10	Q2	app	1340	delivered
KR-00883	C-0053	2026-08-15	Q2	store	1110	delivered
KR-00884	C-0005	2026-09-16	Q2	store	2880	returned
KR-00885	C-0021	2026-07-09	Q2	web	2030	returned
KR-00886	C-0025	2026-08-28	Q2	web	1650	returned
KR-00887	C-0062	2026-09-28	Q2	app	1530	delivered
KR-00888	C-0053	2026-07-18	Q2	web	2210	delivered
KR-00889	C-0092	2026-08-25	Q2	store	2560	delivered
KR-00890	C-0062	2026-09-05	Q2	app	1280	delivered
KR-00891	C-0048	2026-07-24	Q2	web	2900	delivered
KR-00892	C-0044	2026-08-08	Q2	web	1690	delivered
KR-00893	C-0016	2026-09-16	Q2	web	1360	delivered
KR-00894	C-0082	2026-07-01	Q2	web	2550	delivered
KR-00895	C-0104	2026-08-12	Q2	app	1810	delivered
KR-00896	C-0004	2026-09-07	Q2	web	2080	delivered
KR-00897	C-0020	2026-07-05	Q2	app	800	delivered
KR-00898	C-0111	2026-08-13	Q2	web	1200	cancelled
KR-00899	C-0015	2026-09-04	Q2	app	2840	cancelled
KR-00900	C-0031	2026-07-15	Q2	app	870	delivered
KR-00901	C-0022	2026-08-13	Q2	app	2950	delivered
KR-00902	C-0061	2026-09-12	Q2	web	2910	delivered
KR-00903	C-0119	2026-07-13	Q2	store	1220	delivered
KR-00904	C-0112	2026-08-10	Q2	store	2090	cancelled
KR-00905	C-0079	2026-09-23	Q2	web	1010	returned
KR-00906	C-0023	2026-07-22	Q2	store	2200	delivered
KR-00907	C-0030	2026-08-16	Q2	app	890	delivered
KR-00908	C-0087	2026-09-05	Q2	app	2980	cancelled
KR-00909	C-0004	2026-07-12	Q2	app	1520	cancelled
KR-00910	C-0032	2026-08-09	Q2	store	1360	delivered
KR-00911	C-0048	2026-09-03	Q2	web	2200	cancelled
KR-00912	C-0003	2026-07-25	Q2	web	2530	returned
KR-00913	C-0025	2026-08-23	Q2	store	1490	delivered
KR-00914	C-0138	2026-09-08	Q2	store	2760	delivered
KR-00915	C-0113	2026-07-14	Q2	web	1100	delivered
KR-00916	C-0027	2026-08-19	Q2	app	2750	delivered
KR-00917	C-0001	2026-09-27	Q2	store	2390	delivered
KR-00918	C-0041	2026-07-25	Q2	app	1220	delivered
KR-00919	C-0046	2026-08-09	Q2	web	950	delivered
KR-00920	C-0033	2026-09-17	Q2	store	1620	delivered
KR-00921	C-0015	2026-07-20	Q2	web	2570	delivered
KR-00922	C-0011	2026-08-12	Q2	web	2190	delivered
KR-00923	C-0010	2026-09-16	Q2	store	2280	cancelled
KR-00924	C-0021	2026-07-17	Q2	store	1280	delivered
KR-00925	C-0041	2026-08-07	Q2	store	1890	delivered
KR-00926	C-0115	2026-09-05	Q2	store	1760	delivered
KR-00927	C-0055	2026-07-22	Q2	web	1550	delivered
KR-00928	C-0051	2026-08-18	Q2	web	1400	returned
KR-00929	C-0027	2026-09-07	Q2	web	2860	delivered
KR-00930	C-0014	2026-07-17	Q2	app	2550	cancelled
KR-00931	C-0041	2026-08-05	Q2	app	980	delivered
KR-00932	C-0014	2026-09-23	Q2	app	1890	delivered
KR-00933	C-0031	2026-07-23	Q2	app	2990	returned
KR-00934	C-0050	2026-08-08	Q2	store	1490	cancelled
KR-00935	C-0124	2026-09-10	Q2	app	1580	delivered
KR-00936	C-0144	2026-07-02	Q2	store	1320	delivered
KR-00937	C-0148	2026-08-06	Q2	web	2740	delivered
KR-00938	C-0045	2026-09-03	Q2	web	2110	delivered
KR-00939	C-0124	2026-07-16	Q2	app	2630	returned
KR-00940	C-0034	2026-08-24	Q2	app	1260	returned
KR-00941	C-0024	2026-09-17	Q2	web	2550	delivered
KR-00942	C-0019	2026-07-13	Q2	web	1070	delivered
KR-00943	C-0007	2026-08-28	Q2	web	2490	delivered
KR-00944	C-0015	2026-09-17	Q2	web	1490	cancelled
KR-00945	C-0116	2026-07-15	Q2	web	1990	delivered
KR-00946	C-0038	2026-08-10	Q2	app	1630	delivered
KR-00947	C-0015	2026-09-08	Q2	store	1660	delivered
KR-00948	C-0005	2026-07-26	Q2	web	1190	delivered
KR-00949	C-0044	2026-08-08	Q2	app	2520	cancelled
KR-00950	C-0095	2026-09-21	Q2	web	1730	delivered
KR-00951	C-0136	2026-07-01	Q2	web	2220	delivered
KR-00952	C-0110	2026-08-15	Q2	app	1430	delivered
KR-00953	C-0047	2026-09-04	Q2	app	1970	delivered
KR-00954	C-0061	2026-07-17	Q2	web	870	delivered
KR-00955	C-0021	2026-08-27	Q2	store	2090	returned
KR-00956	C-0144	2026-09-10	Q2	store	1880	delivered
KR-00957	C-0026	2026-07-03	Q2	app	1300	delivered
KR-00958	C-0084	2026-08-06	Q2	web	910	delivered
KR-00959	C-0067	2026-09-25	Q2	app	1180	delivered
KR-00960	C-0045	2026-07-13	Q2	web	2360	delivered
KR-00961	C-0134	2026-08-21	Q2	web	1440	delivered
KR-00962	C-0024	2026-09-07	Q2	store	2400	delivered
KR-00963	C-0062	2026-07-16	Q2	store	1740	returned
KR-00964	C-0050	2026-08-02	Q2	web	1490	returned
KR-00965	C-0004	2026-09-04	Q2	store	1380	delivered
KR-00966	C-0031	2026-07-09	Q2	app	1930	delivered
KR-00967	C-0024	2026-08-26	Q2	app	1630	returned
KR-00968	C-0033	2026-09-24	Q2	web	1290	delivered
KR-00969	C-0074	2026-07-20	Q2	store	1950	delivered
KR-00970	C-0018	2026-08-20	Q2	app	2250	cancelled
KR-00971	C-0050	2026-09-15	Q2	web	2110	delivered
KR-00972	C-0022	2026-07-09	Q2	app	1870	cancelled
KR-00973	C-0037	2026-08-22	Q2	web	1190	delivered
KR-00974	C-0096	2026-09-05	Q2	web	1070	delivered
KR-00975	C-0100	2026-07-13	Q2	web	1270	delivered
KR-00976	C-0144	2026-08-04	Q2	app	1970	delivered
KR-00977	C-0043	2026-09-10	Q2	app	1520	delivered
KR-00978	C-0050	2026-07-06	Q2	app	980	delivered
KR-00979	C-0043	2026-08-10	Q2	store	970	delivered
KR-00980	C-0038	2026-09-03	Q2	store	2040	delivered
KR-00981	C-0094	2026-07-17	Q2	web	2980	delivered
KR-00982	C-0133	2026-08-10	Q2	store	2690	delivered
KR-00983	C-0043	2026-09-11	Q2	store	1410	delivered
KR-00984	C-0090	2026-07-28	Q2	store	2740	cancelled
KR-00985	C-0023	2026-08-28	Q2	store	2210	delivered
KR-00986	C-0042	2026-09-19	Q2	web	2270	cancelled
KR-00987	C-0084	2026-07-09	Q2	app	1570	cancelled
KR-00988	C-0020	2026-08-27	Q2	web	1150	returned
KR-00989	C-0030	2026-09-14	Q2	web	2700	returned
KR-00990	C-0019	2026-07-05	Q2	store	2310	delivered
KR-00991	C-0015	2026-08-10	Q2	web	2760	returned
KR-00992	C-0119	2026-09-06	Q2	store	2820	delivered
\.

COPY takehome.plan_line (week_start, plan_revenue) FROM stdin;
2026-07-06	7240000
2026-07-13	7240000
2026-07-20	7240000
2026-07-27	7240000
2026-08-03	7240000
2026-08-10	7240000
2026-08-17	7240000
2026-08-24	7240000
2026-08-31	7240000
2026-09-07	7240000
2026-09-14	7240000
2026-09-21	7240000
2026-09-28	7240000
\.

-- Row counts this file must load:
--   customers: 340
--   orders: 992
--   plan_line: 13
