"""Prints every installed skill with its source and description, and writes docs/skills-catalog.md.
Run at the start of any task: python3 scripts/skills_index.py"""
import pathlib, re

ROOT = pathlib.Path(".claude/skills")
rows = []
for skill_md in sorted(ROOT.glob("*/SKILL.md")):
    text = skill_md.read_text(encoding="utf-8", errors="replace")
    fm = re.search(r"^---\s*(.*?)\s*---", text, re.S)
    name, desc = skill_md.parent.name, ""
    if fm:
        m = re.search(r"^name:\s*(.+)$", fm.group(1), re.M)
        if m:
            name = m.group(1).strip()
        d = re.search(r"^description:\s*[|>]?\s*(.*?)(?=^\w+:|\Z)", fm.group(1), re.M | re.S)
        if d:
            desc = " ".join(d.group(1).split())
    src = skill_md.parent / "SOURCE"
    source = src.read_text().strip() if src.exists() else "unrecorded"
    rows.append((name, source, desc[:220]))

out = ["# Installed skills", "", "Generated by scripts/skills_index.py. One line per skill: name, source, when to use it.", ""]
for name, source, desc in rows:
    out.append(f"- **{name}** ({source}): {desc}")
pathlib.Path("docs").mkdir(exist_ok=True)
pathlib.Path("docs/skills-catalog.md").write_text("\n".join(out) + "\n", encoding="utf-8")
for name, source, desc in rows:
    print(f"{name:40s} {source:30s} {desc[:100]}")
print(f"\n{len(rows)} skills. Catalog written to docs/skills-catalog.md")
