"""Regenerate everything that follows from the programme's movable facts, with one command.

    python3 scripts/sync_programme.py           # check the sources, regenerate, say what changed
    python3 scripts/sync_programme.py --check   # write nothing; exit 1 if anything is stale or wrong

Edit the sources, never the outputs:

    docs/curriculum/source.xlsx   the curriculum tracker: every week and day, the Structure tab,
                                  the 20-Week Plan, the capstone plan and the Saturday item bank
    docs/faculty/source.xlsx      the IITGN faculty session plan, tentative until IITGN confirms
    docs/journey/source.xlsx      the student-facing 20-week journey and Week 0 sheet
    data/programme/facts.yaml     every movable fact the workbooks do not hold, each with a status

The sync checks that the sources agree before it writes anything: every holiday in the facts is a
no-session day in the tracker and the other way round, the 20-Week Plan's dates match the day tabs,
every faculty session sits on a teaching day inside its own week, the violet column of the tracker
and the faculty workbook place each session on the same day, the per-week session counts agree,
and no faculty name reaches the repository while facts.yaml says names stay unpublished. Then it
writes:

    docs/curriculum/*.md, docs/faculty/*.md, docs/journey/*.md   the workbook exports
    data/programme/days.json      one record per day, which scripts/board_sync.py reads
    docs/programme/*.md           the calendar, the faculty plan and the decisions register
    content/W{ww}/SAT/paper and answer-key, for every week whose paper is already built,
                                  with data/programme/paper_edits.yaml laid on top
    every <!-- sync:NAME --> ... <!-- /sync:NAME --> block in the markdown under docs/, content/,
    prompts/, wiki/ and .claude/skills/, plus CLAUDE.md, re-rendered for its file's audience
    docs/claude-project/knowledge/  the files the claude.ai Project is loaded with

When IIT Gandhinagar confirms or moves a session, replace docs/faculty/source.xlsx with the returned
workbook (with the Faculty member column cleared while the repository is public), or add one line
under faculty.overrides in facts.yaml, then run the sync. When a holiday, a status or a decision
changes, edit facts.yaml and run the sync. On GitHub, the programme-sync workflow runs the same
command on any branch that changes a source and commits what it regenerates.

The block names a markdown file can carry, and what each renders:

    sync:status                    the one-line state of the movable facts, with its date
    sync:calendar-summary          the week table: dates, kind, module, holidays, faculty sessions
    sync:faculty-summary           the faculty plan by week, with statuses
    sync:evaluation                the evaluation proposals and their status (never in STUDENT files)
    sync:decisions                 the open decisions and the known conflicts (never in STUDENT files)
    sync:module:W02/D1             the module a day posts to, as "Module 1: Foundations of AI and Data"
    sync:day-date:W02/D1           the day's date, as "Mon 12 Oct 2026"
    sync:faculty-day:W02/D1        that day's IITGN block, or a line saying there is none
    sync:rubric:W03                a build's settled rubrics and graded days, from evaluation.rubrics
    sync:rubric:W03/mock           one of them: mini-project, mock or gd

A file's audience comes from its name: _STUDENT, _TRAINER or _INTERNAL, and INTERNAL for anything
else. A STUDENT file never receives a proposed or open fact, and a tentative one arrives with the
word tentative beside it.
"""
import argparse
import datetime as dt
import json
import os
import pathlib
import re
import sys

import openpyxl
import yaml

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(HERE))
import build_saturday_paper as bsp  # noqa: E402
import export_curriculum as ec  # noqa: E402

FACTS = pathlib.Path("data/programme/facts.yaml")
DAYS_JSON = pathlib.Path("data/programme/days.json")
TRACKER = pathlib.Path("docs/curriculum/source.xlsx")
FACULTY = pathlib.Path("docs/faculty/source.xlsx")
JOURNEY = pathlib.Path("docs/journey/source.xlsx")
PROGRAMME_DOCS = pathlib.Path("docs/programme")
PROJECT_PACK = pathlib.Path("docs/claude-project/knowledge")
SCAN = ["docs", "content", "prompts", "wiki", ".claude/skills"]
SCAN_FILES = ["CLAUDE.md", "README.md"]
SKIP_PARTS = {".claude/worktrees", "docs/curriculum", "docs/faculty", "docs/journey",
              "docs/programme", "docs/claude-project/knowledge"}

WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
HOLIDAY_SLOT = {0: "MON", 1: "TUE", 2: "WED", 3: "THU", 4: "FRI"}
VIOLET = "IITGN faculty session (TENTATIVE)"
SESSION_ID = re.compile(r"\bsession (W\d+-\d+)\b")
NO_NAME = {"", "to be confirmed", "tbc", "none", "none yet"}
GENERATED = "Generated by scripts/sync_programme.py from the sources it names. Edit those, then sync."


class Report:
    def __init__(self):
        self.errors, self.warnings = [], []

    def error(self, text):
        self.errors.append(text)

    def warn(self, text):
        self.warnings.append(text)


def iso(d):
    return d.isoformat() if d else None


def long_date(d):
    return d.strftime("%a %d %b %Y")


def short_date(d):
    return d.strftime("%a %d %b")


def week_key(n):
    return f"W{n:02d}"


def as_date(value):
    if isinstance(value, dt.datetime):
        return value.date()
    if isinstance(value, dt.date):
        return value
    if isinstance(value, str) and value.strip():
        return dt.date.fromisoformat(value.strip()[:10])
    return None


# --------------------------------------------------------------------------- reading the sources
def load_facts():
    facts = yaml.safe_load(FACTS.read_text(encoding="utf-8"))
    for key in ("calendar", "faculty", "evaluation", "modules", "decisions", "conflicts"):
        if key not in facts:
            sys.exit(f"FAIL  {FACTS} has no '{key}' section")
    return facts


def read_tracker_days(wb, facts, report):
    """Every day row of every day tab, as dicts, plus the capstone weeks as week-level records."""
    holidays = {as_date(h["date"]): h["name"] for h in facts["calendar"]["holidays"]}
    modules = facts["modules"]["weeks"]
    exceptions = facts["modules"].get("day_exceptions") or {}
    days, weeks = [], {}
    for ws in wb.worksheets:
        shape = ec.shape_of(ws)
        if shape not in ("days", "weekly"):
            continue
        n = int(re.match(r"^W(\d+)", ws.title).group(1))
        if shape == "weekly":
            continue
        headers = ec.headers_of(ws)
        col = {h: i + 1 for i, h in enumerate(headers) if h}
        kind_of_week = ("baseline" if n == 0 else
                        "build-week" if re.search(r"\bBuild\b", ws.title) else "teaching")
        for r in range(ec.FIRST_DATA_ROW, ws.max_row + 1):
            raw = ec.clean(ws.cell(row=r, column=col["Day"]).value)
            if not raw:
                continue
            parts = raw.split("\n")
            date = dt.datetime.strptime(parts[-1].strip(), "%d %b %Y").date()
            if date.strftime("%a") != parts[0].strip()[:3]:
                report.error(f"{ws.title}: '{raw}' names the wrong weekday for its date")
            focus_cell = ec.clean(ws.cell(row=r, column=col["Day focus"]).value)
            topic, _, focus = focus_cell.partition(" · ")
            if not focus:
                topic, focus = "", topic
            wd = date.weekday()
            says_off = bool(re.search(r"no session", focus_cell, re.I))
            if date in holidays and not says_off:
                report.error(f"{ws.title}: {long_date(date)} is {holidays[date]} in facts.yaml, "
                             f"but the tracker row teaches")
            if says_off and date not in holidays:
                report.error(f"{ws.title}: {long_date(date)} says no session, but facts.yaml has no "
                             f"holiday on that date")
            if date in holidays:
                kind, slot = "holiday", HOLIDAY_SLOT[wd]
            elif wd == 5:
                slot = "SAT"
                kind = ("saturday" if kind_of_week == "teaching" and topic.lower().startswith("saturday")
                        else kind_of_week)
            else:
                kind, slot = kind_of_week, f"D{wd + 1}"
            violet = ec.clean(ws.cell(row=r, column=col[VIOLET]).value) if VIOLET in col else ""
            key = f"{week_key(n)}/{slot}"
            days.append({
                "week": week_key(n), "slot": slot, "date": date, "weekday": WEEKDAYS[wd],
                "kind": kind, "topic": topic.strip(), "focus": focus.strip(),
                "module": exceptions.get(key, modules.get(week_key(n))),
                "holiday": holidays.get(date), "violet": violet,
                "violet_ids": SESSION_ID.findall(violet), "tab": ws.title,
            })
        weeks[week_key(n)] = {"number": n, "kind": kind_of_week, "tab": ws.title}
    return days, weeks


def read_capstone(wb, facts):
    """The capstone tab's week rows: 'Wk 17\\n25 to 30 Jan 2027\\nFrame, propose, ...'."""
    out = {}
    monday1 = as_date(facts["calendar"]["week1_monday"])
    for ws in wb.worksheets:
        if ec.shape_of(ws) != "weekly":
            continue
        for r in range(ec.FIRST_DATA_ROW, ws.max_row + 1):
            cell = ec.clean(ws.cell(row=r, column=1).value)
            m = re.match(r"^Wk (\d+)\n", cell)
            if not m or "Sat" in cell.split("\n")[0]:
                continue
            n = int(m.group(1))
            lines = [p.strip() for p in cell.split("\n") if p.strip()]
            monday = monday1 + dt.timedelta(weeks=n - 1)
            out[week_key(n)] = {"number": n, "kind": "capstone", "tab": ws.title,
                                "monday": monday, "focus": lines[-1]}
    return out


def read_plan(wb):
    """The 20-Week Plan's grid, keyed W00 to W20."""
    ws = wb[ec.PLAN_TAB]
    header_row = next(r for r in range(1, ws.max_row + 1)
                      if ec.clean(ws.cell(row=r, column=1).value) == ec.PLAN_FIRST_HEADER)
    headers = ec.headers_of(ws, header_row)
    out = {}
    for r in range(header_row + 1, ws.max_row + 1):
        first = ec.clean(ws.cell(row=r, column=1).value)
        if not re.fullmatch(r"\d+", first):
            break
        row = {headers[c - 1]: ec.clean(ws.cell(row=r, column=c).value)
               for c in range(1, len(headers) + 1) if headers[c - 1]}
        out[week_key(int(first))] = row
    return out


def parse_span(text, year_hint):
    """'05 to 10 Oct 2026', '28 Sep to 03 Oct 2026' or '28 Dec 2026 to 02 Jan 2027' as two dates."""
    first = text.split("\n")[0].strip()
    m = re.match(r"^(\d{1,2})(?: ([A-Z][a-z]{2}))?(?: (\d{4}))? to (\d{1,2}) ([A-Z][a-z]{2}) (\d{4})$", first)
    if not m:
        return None, None
    d1, mon1, y1, d2, mon2, y2 = m.groups()
    end = dt.datetime.strptime(f"{d2} {mon2} {y2}", "%d %b %Y").date()
    start = dt.datetime.strptime(f"{d1} {mon1 or mon2} {y1 or y2}", "%d %b %Y").date()
    return start, end


def read_faculty(path, facts, report):
    """The Sessions tab, one dict per session, with facts.yaml overrides laid on top."""
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["Sessions"]
    header_row = next(r for r in range(1, ws.max_row + 1)
                      if ec.clean(ws.cell(row=r, column=1).value) == "Session")
    headers = ec.headers_of(ws, header_row)
    col = {h: i + 1 for i, h in enumerate(headers) if h}
    sessions, banner, progress = [], "", ""
    publish = bool(facts["faculty"].get("publish_names"))
    for r in range(header_row + 1, ws.max_row + 1):
        first = ec.clean(ws.cell(row=r, column=1).value)
        if first.startswith("WEEK "):
            banner = first
            continue
        if first.startswith("Learner progress"):
            progress = first
            continue
        if not re.fullmatch(r"W\d+-\d+", first):
            continue
        get = lambda name: ec.clean(ws.cell(row=r, column=col[name]).value) if name in col else ""
        s = {
            "id": first, "week": week_key(int(get("Week") or 0)),
            "date": as_date(ws.cell(row=r, column=col["Date"]).value),
            "minutes": int(float(get("Duration (min)") or 0)),
            "module_subject": get("Module and subject"), "topic": get("Session topic"),
            "subtopics": get("Subtopics"), "outcomes": get("Learning outcomes"),
            "place": get("Place in the programme"), "prior": get("Prior coverage"),
            "reserved": get("Reserved for later sessions"), "references": get("Suggested references"),
            "faculty": get("Faculty member"), "status": get("Status") or "Tentative",
            "remarks": get("Remarks"), "banner": banner, "progress": progress, "row": r,
            "overridden": False,
        }
        if s["faculty"].lower() not in NO_NAME and not publish:
            report.error(f"{path} row {r} names a faculty member for {s['id']}, and facts.yaml says "
                         f"faculty.publish_names is false. The repository is public: clear that "
                         f"column before committing the workbook, or make the repository private "
                         f"and set publish_names to true.")
        sessions.append(s)
    for sid, change in (facts["faculty"].get("overrides") or {}).items():
        hit = next((s for s in sessions if s["id"] == sid), None)
        if not hit:
            report.error(f"facts.yaml faculty.overrides names {sid}, which the workbook does not have")
            continue
        for k, v in change.items():
            hit[k] = as_date(v) if k == "date" else v
        hit["overridden"] = True
        if (hit.get("faculty") or "").lower() not in NO_NAME and not publish:
            report.error(f"facts.yaml overrides {sid} with a faculty name while publish_names is false")
    overview = {}
    ov = wb["Overview"]
    for r in range(1, ov.max_row + 1):
        if ec.clean(ov.cell(row=r, column=1).value) == "Input":
            overview[ec.clean(ov.cell(row=r, column=2).value)] = ov.cell(row=r, column=3).value
    return sessions, overview, wb


# --------------------------------------------------------------------------- checking them
def check_calendar(days, plan, capstone, facts, report):
    monday1 = as_date(facts["calendar"]["week1_monday"])
    monday0 = as_date(facts["calendar"]["week0_monday"])
    if monday1 - monday0 != dt.timedelta(weeks=1):
        report.error("facts.yaml: week0_monday is not the Monday before week1_monday")
    by_week = {}
    for d in days:
        by_week.setdefault(d["week"], []).append(d)
    for wk, row in plan.items():
        n = int(wk[1:])
        want_mon = monday0 if n == 0 else monday1 + dt.timedelta(weeks=n - 1)
        start, end = parse_span(row.get("Dates (Mon to Sat)", ""), want_mon.year)
        if start != want_mon or end != want_mon + dt.timedelta(days=5):
            report.error(f"20-Week Plan: week {n} prints '{row.get('Dates (Mon to Sat)', '')}', "
                         f"but the calendar puts it at {short_date(want_mon)} to "
                         f"{long_date(want_mon + dt.timedelta(days=5))}")
        if wk in by_week:
            got = sorted(d["date"] for d in by_week[wk])
            if got[0] != want_mon or got[-1] != want_mon + dt.timedelta(days=5) or len(got) != 6:
                report.error(f"{by_week[wk][0]['tab']}: its days do not run Monday to Saturday of "
                             f"the week the calendar gives it")
        elif wk not in capstone:
            report.error(f"20-Week Plan has week {n}, but the tracker has no tab for it")
    last = as_date(facts["calendar"]["last_day"])
    if plan and max(int(w[1:]) for w in plan) != (last - monday1).days // 7 + 1:
        report.error("facts.yaml last_day does not fall in the plan's last week")
    for h in facts["calendar"]["holidays"]:
        date = as_date(h["date"])
        if not any(d["date"] == date for d in days) and not any(
                c["monday"] <= date <= c["monday"] + dt.timedelta(days=5) for c in capstone.values()):
            report.error(f"facts.yaml holiday {h['name']} on {long_date(date)} falls on no programme day")


def check_faculty(sessions, days, plan, facts, report):
    by_date = {d["date"]: d for d in days}
    per_week, seen = {}, set()
    minutes = facts["faculty"].get("session_minutes", 120)
    for s in sessions:
        if s["id"] in seen:
            report.error(f"faculty workbook: {s['id']} appears twice")
        seen.add(s["id"])
        per_week[s["week"]] = per_week.get(s["week"], 0) + 1
        day = by_date.get(s["date"])
        if not s["date"] or not day:
            report.error(f"{s['id']}: its date {s['date']} is not a programme day")
            continue
        s["slot"] = f"{day['week']}/{day['slot']}"
        if day["week"] != s["week"]:
            report.error(f"{s['id']}: dated {long_date(s['date'])}, which is in {day['week']}, "
                         f"not {s['week']}")
        if day["kind"] != "teaching" or day["weekday"] == "Sat":
            what = {"saturday": "the Saturday recap", "holiday": f"a holiday ({day['holiday']})",
                    "build-week": "a build-week day", "baseline": "in the baseline week"}.get(
                        day["kind"], "a Saturday")
            report.error(f"{s['id']}: {long_date(s['date'])} is {what}, and a faculty block runs "
                         f"on a weekday teaching day only")
        if s["minutes"] != minutes:
            report.warn(f"{s['id']} runs {s['minutes']} minutes against the planned {minutes}")
        if s["id"] not in day["violet_ids"]:
            placed = [d for d in days if s["id"] in d["violet_ids"]]
            where = f"{placed[0]['week']}/{placed[0]['slot']}" if placed else "no day"
            source = "facts.yaml overrides it to" if s["overridden"] else "the faculty workbook puts it on"
            text = (f"{s['id']}: {source} {long_date(s['date'])} ({s['slot']}); the tracker's "
                    f"violet column puts it on {where}.")
            if s["overridden"]:
                report.warn(text + " The override in facts.yaml wins until the tracker catches up.")
            else:
                report.warn(text + " The workbook wins; update the tracker's violet column.")
    ids = {s["id"] for s in sessions}
    for d in days:
        for sid in d["violet_ids"]:
            if sid not in ids:
                report.error(f"{d['tab']}: {short_date(d['date'])} names session {sid}, which the "
                             f"faculty workbook does not have")
    for wk, row in plan.items():
        want = int(float(row.get("IITGN sessions (tentative)") or 0))
        if per_week.get(wk, 0) != want:
            report.error(f"20-Week Plan gives week {int(wk[1:])} {want} IITGN sessions; the faculty "
                         f"workbook has {per_week.get(wk, 0)}")
    total_hours = sum(s["minutes"] for s in sessions) / 60
    if total_hours != facts["faculty"].get("hours_committed"):
        report.warn(f"the faculty sessions add to {total_hours:g} hours against "
                    f"{facts['faculty'].get('hours_committed')} committed")
    doubles = {}
    for s in sessions:
        doubles.setdefault(s["date"], []).append(s["id"])
    for date, sids in doubles.items():
        if len(sids) > 1:
            report.warn(f"{long_date(date)} carries {len(sids)} faculty sessions: {', '.join(sids)}")


# --------------------------------------------------------------------------- the context
class Context:
    def __init__(self, facts, days, weeks, capstone, plan, sessions):
        self.facts, self.days, self.weeks, self.capstone = facts, days, weeks, capstone
        self.plan, self.sessions = plan, sessions
        self.day = {f"{d['week']}/{d['slot']}": d for d in days}
        self.violet_text = {}
        for d in days:
            for sid in d["violet_ids"]:
                self.violet_text[sid] = d["violet"]

    def module_name(self, code):
        if not code:
            return "no module, since Week 0 sits outside the 510 hours"
        n = code[1:]
        return f"Module {n}: {self.facts['modules']['names'][code]}"

    def sessions_on(self, date):
        return [s for s in self.sessions if s["date"] == date]

    def faculty_label(self, s):
        name = (s.get("faculty") or "").strip()
        if name.lower() in NO_NAME:
            return "to be confirmed by IIT Gandhinagar"
        if self.facts["faculty"].get("publish_names"):
            return name
        return "named in the workbook, not published here"

    def status_word(self, s):
        return (s.get("status") or "Tentative").strip().lower()


def week_monday(ctx, wk):
    if wk in ctx.capstone:
        return ctx.capstone[wk]["monday"]
    return min(d["date"] for d in ctx.days if d["week"] == wk)


def week_label(ctx, wk):
    row = ctx.plan.get(wk, {})
    return row.get("Focus", "").split("\n")[0]


# --------------------------------------------------------------------------- the renderers
def render_status(ctx, arg, audience):
    f = ctx.facts
    confirmed = sum(1 for s in ctx.sessions if ctx.status_word(s) == "confirmed")
    opened = sum(1 for d in f["decisions"] if d.get("status") == "open")
    parts = [f"Facts as of {dt.date.fromisoformat(str(f['as_of'])).strftime('%d %b %Y')}: "
             f"calendar {f['calendar']['status']} on "
             f"{as_date(f['calendar']['locked_on']).strftime('%d %b %Y')}",
             f"IITGN faculty sessions {len(ctx.sessions)} planned, {confirmed} confirmed",
             f"client zero {f['client_zero']['locked']['version']} locked and "
             f"{f['client_zero']['proposed']['version']} {f['client_zero']['proposed']['status']}"]
    if audience != "STUDENT":
        parts += [f"evaluation {f['evaluation']['status']}", f"{opened} decisions open"]
    return "; ".join(parts) + "."


def render_calendar_summary(ctx, arg, audience):
    rows = []
    for wk in sorted(set(ctx.plan) | set(ctx.capstone)):
        n = int(wk[1:])
        mon = week_monday(ctx, wk)
        sat = mon + dt.timedelta(days=5)
        kind = (ctx.capstone[wk]["kind"] if wk in ctx.capstone else ctx.weeks[wk]["kind"])
        offs = [f"{short_date(d['date'])}, {d['holiday']}" for d in ctx.days
                if d["week"] == wk and d["holiday"]]
        offs += [f"{short_date(as_date(h['date']))}, {h['name']}" for h in ctx.facts["calendar"]["holidays"]
                 if wk in ctx.capstone and mon <= as_date(h["date"]) <= sat]
        sess = [s for s in ctx.sessions if s["week"] == wk]
        if sess:
            conf = sum(1 for s in sess if ctx.status_word(s) == "confirmed")
            fac = f"{len(sess)} ({conf} confirmed)" if audience != "STUDENT" or conf else f"{len(sess)}, tentative"
        else:
            fac = "none"
        module = ctx.facts["modules"]["weeks"].get(wk)
        rows.append([str(n), f"{mon.strftime('%d %b')} to {sat.strftime('%d %b %Y')}", kind,
                     module or "none", week_label(ctx, wk), "; ".join(offs) or "none", fac])
    head = ["Week", "Mon to Sat", "Kind", "Module", "Focus", "Holidays", "IITGN sessions"]
    return "\n".join(ec.md_table(head, rows))


def render_faculty_summary(ctx, arg, audience):
    f = ctx.facts["faculty"]
    lines = [f"Status: {f['status']} until {f['confirms']}. {len(ctx.sessions)} sessions of "
             f"{f['session_minutes']} minutes, {sum(s['minutes'] for s in ctx.sessions) / 60:g} hours "
             f"against {f['hours_committed']} committed. {f['placement']}", ""]
    rows = []
    for s in ctx.sessions:
        rows.append([s["id"], short_date(s["date"]), s.get("slot", ""), s["topic"],
                     s["status"] + (" (override)" if s["overridden"] else ""),
                     ctx.faculty_label(s)])
    lines += ec.md_table(["Session", "Date", "Day", "Topic", "Status", "Faculty"], rows)
    if audience != "STUDENT" and f.get("ruling", {}).get("status") == "open":
        lines += ["", f"Open ruling: {f['ruling']['text']}"]
    return "\n".join(lines)


def render_evaluation(ctx, arg, audience):
    if audience == "STUDENT":
        raise ValueError("the evaluation block never renders in a STUDENT file")
    ev = ctx.facts["evaluation"]
    comps = ["major_exams", "mini_projects", "mock_interviews", "business_gds", "capstone"]
    head = ["Version", "Status", "Major exams", "Mini projects", "Mock interviews", "Business GDs",
            "Capstone", "Source"]
    rows = []
    for v in ev["versions"]:
        rows.append([v["id"], v["status"]] + [str(v["components"][c]) for c in comps] + [v["source"]])
    exams = "; ".join(f"{k} in Week {v['week']}, {v['marks']} marks, posting to {v['posts_to']}"
                      + (f", {v['when']}" if v.get("when") else "") for k, v in ev["exams"].items())
    att = ev.get("attendance")
    rub = ev.get("rubrics") or {}
    settled = [f"Rubrics settled: " + "; ".join(f"{v['build']} ({k}), {v['status']}, by {v['settled']}"
                                                for k, v in rub.items())
               + ". Every other rubric waits for the programme handbook."] if rub else []
    return "\n".join([f"Status: {ev['status']}. {ev['rule']} The version in force is {ev['current']}.",
                      ""] + ec.md_table(head, rows) +
                     ["", f"Exams, {ev['exams']['ME1']['status']}: {exams}.",
                      f"Exam day and slot: {ev['exam_day_and_slot']['status']}. "
                      f"{ev['exam_day_and_slot']['rule']}",
                      f"Ungraded indicators: {', '.join(ev['ungraded'])}."] +
                     ([f"Attendance, {att['status']}: {att['minimum']} minimum over {att['over']}, "
                       f"recorded {att['recorded']}."] if att else []) + settled)


def render_decisions(ctx, arg, audience):
    if audience == "STUDENT":
        raise ValueError("the decisions block never renders in a STUDENT file")
    rows = [[d["id"], d["status"], d["closes"], d["text"], d["blocks"]] for d in ctx.facts["decisions"]]
    lines = ["Open decisions:", ""] + ec.md_table(["Decision", "Status", "Closed by", "What",
                                                   "What it blocks"], rows)
    rows = [[c["id"], ", ".join(c["sources"]), c["text"], c["working_rule"]]
            for c in ctx.facts["conflicts"]]
    lines += ["", "Known conflicts between the sources, and the working rule until one is fixed:", ""]
    lines += ec.md_table(["Conflict", "Sources", "What disagrees", "Working rule"], rows)
    return "\n".join(lines)


def render_rubric(ctx, arg, audience):
    """A build's settled rubrics: all of them for W03, one for W03/mock. The marks must add up."""
    week, _, event = arg.partition("/")
    entry = (ctx.facts["evaluation"].get("rubrics") or {}).get(week)
    if not entry:
        raise ValueError(f"no settled rubric for {week}; it waits for the programme handbook")
    if audience == "STUDENT" and (entry["status"] != "locked" or entry.get("learner_facing") != "allowed"):
        raise ValueError(f"the {week} rubrics are not open to learners")
    events = entry["events"]
    if event and event not in events:
        raise ValueError(f"no {event} rubric for {week}; the events are {', '.join(events)}")
    out = []
    for key in [event] if event else list(events):
        e = events[key]
        at = e["columns"].index("Marks")
        total = sum(int(row[at]) for row in e["criteria"])
        if total != e["marks"]:
            raise ValueError(f"the {week} {key} criteria add to {total}, not {e['marks']}")
        out += ([""] if out else []) + [f"**{e['title']}, {e['marks']} marks.** {e['scored']}", ""]
        out += ec.md_table(e["columns"], [[str(c) for c in row] for row in e["criteria"]])
    if not event:
        days = entry.get("graded_days") or {}
        out += ["", " ".join(days.values())] if days else []
        if audience != "STUDENT":
            out += ["", f"{entry['build']}'s rubrics are {entry['status']}, settled by {entry['settled']}."]
    return "\n".join(out)


def need_day(ctx, arg):
    if arg not in ctx.day:
        raise ValueError(f"no day {arg} in the calendar")
    return ctx.day[arg]


def render_module(ctx, arg, audience):
    if "/" in arg:
        return ctx.module_name(need_day(ctx, arg)["module"])
    return ctx.module_name(ctx.facts["modules"]["weeks"].get(arg))


def render_day_date(ctx, arg, audience):
    return long_date(need_day(ctx, arg)["date"])


def render_faculty_day(ctx, arg, audience):
    day = need_day(ctx, arg)
    here = ctx.sessions_on(day["date"])
    moved = [s for s in ctx.sessions if s["id"] in day["violet_ids"] and s["date"] != day["date"]]
    if audience == "STUDENT":
        if not here:
            return "No IITGN faculty session today."
        out = []
        for s in here:
            word = "confirmed" if ctx.status_word(s) == "confirmed" else "tentative"
            out.append(f"After today's applied session, an IITGN faculty session ({word}) takes the "
                       f"theory further: {s['topic']}, {s['minutes']} minutes.")
        return " ".join(out)
    out = []
    for s in here:
        out.append(f"**IITGN faculty block {s['id']} ({ctx.status_word(s)}), {s['minutes']} minutes, "
                   f"after this row's applied core.** Faculty: {ctx.faculty_label(s)}."
                   + (f" Remarks: {s['remarks']}." if s.get("remarks") and
                      s["remarks"].lower() not in NO_NAME else ""))
        text = ctx.violet_text.get(s["id"], "")
        body = [ln for ln in text.split("\n")[1:] if ln.strip()] if text else []
        out += [""] + (body or [f"TOPIC: {s['topic']}."])
        f = ctx.facts["faculty"]
        if f.get("ruling", {}).get("status") == "open":
            out += ["", f"Open ruling: {f['ruling']['text']}"]
    for s in moved:
        out.append(f"{s['id']} was planned for this day and now sits on {long_date(s['date'])} "
                   f"({s['slot']}).")
    return "\n".join(out) if out else "No IITGN faculty block on this day."


RENDERERS = {
    "status": render_status,
    "calendar-summary": render_calendar_summary,
    "faculty-summary": render_faculty_summary,
    "evaluation": render_evaluation,
    "decisions": render_decisions,
    "module": render_module,
    "day-date": render_day_date,
    "faculty-day": render_faculty_day,
    "rubric": render_rubric,
}

OPEN = re.compile(r"<!-- sync:([a-z-]+)(?::([A-Za-z0-9/_-]+))? -->")
FENCE = re.compile(r"^(```|~~~).*?^\1[ \t]*$", re.M | re.S)


def audience_of(path):
    m = re.search(r"_(STUDENT|TRAINER|INTERNAL)\.", path.name)
    return m.group(1) if m else "INTERNAL"


def render_blocks(text, ctx, path, report):
    """Rewrite every sync block in one file. Inline blocks stay inline; block ones keep their lines."""
    out, pos = [], 0
    audience = audience_of(path)
    # A block inside a fenced code example is documentation of the syntax, never a live block.
    fences = [(f.start(), f.end()) for f in FENCE.finditer(text)]
    for m in OPEN.finditer(text):
        if m.start() < pos or any(a <= m.start() < b for a, b in fences):
            continue
        line_start = text.rfind("\n", 0, m.start()) + 1
        if text.count("`", line_start, m.start()) % 2:
            continue  # inside an inline code span, so it is an example
        name, arg = m.group(1), m.group(2) or ""
        tag = name + (":" + arg if arg else "")
        close = f"<!-- /sync:{tag} -->"
        end = text.find(close, m.end())
        if end < 0:
            report.error(f"{path}: <!-- sync:{tag} --> has no closing {close}")
            continue
        renderer = RENDERERS.get(name)
        if not renderer:
            report.error(f"{path}: unknown sync block '{name}'")
            continue
        try:
            body = renderer(ctx, arg, audience)
        except ValueError as e:
            report.error(f"{path}: sync:{tag}: {e}")
            continue
        inner = text[m.end():end]
        block = "\n" in inner or "\n" in body
        new_inner = f"\n{body}\n" if block else body
        out += [text[pos:m.end()], new_inner, close]
        pos = end + len(close)
    out.append(text[pos:])
    return "".join(out)


def marker_files():
    seen = []
    for base in SCAN:
        for p in sorted(pathlib.Path(base).rglob("*.md")):
            s = p.as_posix()
            if any(s.startswith(skip) for skip in SKIP_PARTS):
                continue
            seen.append(p)
    return seen + [pathlib.Path(f) for f in SCAN_FILES if pathlib.Path(f).exists()]


# --------------------------------------------------------------------------- generated pages
def page(title, intro, body):
    return "\n".join([f"# {title}", "", f"<!-- {GENERATED} -->", "", intro, "", body, ""])


def calendar_page(ctx):
    lines = [render_calendar_summary(ctx, "", "INTERNAL"), "", "## Every day", "",
             "The slot is the day's folder under content/W{ww}/ and its board card. A teaching or "
             "build day is D1 to D5 by weekday, a holiday keeps the weekday's name, every Saturday "
             "is SAT, and a capstone week is planned at the week level as WEEK.", ""]
    rows = []
    for d in ctx.days:
        sess = ", ".join(f"{s['id']} ({ctx.status_word(s)})" for s in ctx.sessions_on(d["date"]))
        rows.append([f"{d['week']}/{d['slot']}", short_date(d["date"]), d["kind"],
                     d["module"] or "none", d["topic"] or d["kind"], d["focus"], sess or "none"])
    for wk, c in sorted(ctx.capstone.items()):
        rows.append([f"{wk}/WEEK", f"{short_date(c['monday'])} to "
                     f"{short_date(c['monday'] + dt.timedelta(days=5))}", "capstone",
                     ctx.facts["modules"]["weeks"].get(wk) or "none", "Capstone", c["focus"], "none"])
    lines += ec.md_table(["Day", "Date", "Kind", "Module", "Topic", "Focus", "IITGN session"], rows)
    restricted = ctx.facts["calendar"].get("restricted") or []
    if restricted:
        lines += ["", "Restricted holidays, which the institute calendar decides: " + "; ".join(
            f"{long_date(as_date(h['date']))}, {h['name']}" for h in restricted) + "."]
    return page("Programme calendar",
                f"Week 0 runs from {long_date(as_date(ctx.facts['calendar']['week0_monday']))}, "
                f"teaching Week 1 starts on {long_date(as_date(ctx.facts['calendar']['week1_monday']))} "
                f"and the programme closes on {long_date(as_date(ctx.facts['calendar']['last_day']))}. "
                f"The calendar is {ctx.facts['calendar']['status']} "
                f"({ctx.facts['calendar']['source']}).",
                "\n".join(lines))


def faculty_page(ctx, report):
    lines = [render_faculty_summary(ctx, "", "INTERNAL"), ""]
    lines += ["## Cross-check against the tracker", ""]
    notes = [w for w in report.warnings if re.match(r"^W\d+-\d+", w)]
    lines += (["- " + n for n in notes] if notes else
              ["Every session sits on the same day in the faculty workbook and in the tracker's violet "
               "column, each on a teaching day inside its own week, and the per-week counts match the "
               "20-Week Plan."])
    lines += ["", "## Per session", ""]
    for s in ctx.sessions:
        lines += [f"### {s['id']} · {long_date(s['date'])} · {s['topic']}", "",
                  f"Day: {s.get('slot', '')}. Status: {s['status']}"
                  + (" (from the override in facts.yaml)" if s["overridden"] else "")
                  + f". Faculty: {ctx.faculty_label(s)}. {s['module_subject'].replace(chr(10), '. ')}.",
                  ""]
        for label, key in [("Learning outcomes", "outcomes"), ("Prior coverage", "prior"),
                           ("Reserved for later", "reserved")]:
            if s.get(key):
                lines += [f"{label}: {s[key]}", ""]
    return page("IITGN faculty plan",
                "Every session is tentative until IIT Gandhinagar confirms the faculty member and "
                "the date. The full session plan, with subtopics and references, is "
                "docs/faculty/Sessions.md.", "\n".join(lines))


def decisions_page(ctx):
    f = ctx.facts
    body = [render_decisions(ctx, "", "INTERNAL"), "", "## Evaluation", "",
            render_evaluation(ctx, "", "INTERNAL"), "", "## Client zero", "",
            f"Locked: {f['client_zero']['locked']['version']} on "
            f"{as_date(f['client_zero']['locked']['locked_on']).strftime('%d %b %Y')}. Proposed: "
            f"{f['client_zero']['proposed']['version']}, which carries:", ""]
    body += ["- " + i for i in f["client_zero"]["proposed"]["items"]]
    body += ["", "Still open inside it: " + "; ".join(f["client_zero"]["proposed"]["open"]) + "."]
    for a in f["client_zero"].get("addenda", []):
        body += ["", f"Addendum to {f['client_zero']['locked']['version']}, {a['status']} on "
                 f"{as_date(a['decided_on']).strftime('%d %b %Y')} by {a['by']}: {a['text']}"]
    body += ["", f"## The re-cut of {as_date(f['recut']['made_on']).strftime('%d %B %Y')} "
             f"({f['recut']['status']})", "", f["recut"]["note"], ""]
    body += ["- " + i for i in f["recut"]["items"]]
    return page("Decisions register", "What is still open, what disagrees, and what is proposed, "
                "with the working rule for each. Roles only.", "\n".join(body))


def faculty_exports(path):
    """The faculty workbook as markdown: Overview plain, Sessions per session, references as a table."""
    wb = openpyxl.load_workbook(path, data_only=True)
    files = {}
    for ws in wb.worksheets:
        name = ec.file_name(ws.title)
        if ws.title == "Reference library":
            hr = next(r for r in range(1, ws.max_row + 1) if ec.clean(ws.cell(row=r, column=1).value) == "Ref")
            headers = [h for h in ec.headers_of(ws, hr) if h]
            rows = [[ws.cell(row=r, column=c).value for c in range(1, len(headers) + 1)]
                    for r in range(hr + 1, ws.max_row + 1) if ws.cell(row=r, column=1).value]
            lines = ["# " + ws.title, ""] + [ec.clean(ws.cell(row=r, column=1).value)
                                             for r in range(1, hr) if ws.cell(row=r, column=1).value]
            lines += [""] + ec.md_table(headers, rows) + [""]
            files[name] = "\n".join(lines)
        else:
            files[name] = "\n".join(ec.export_plain(ws)[0])
    return files


def redact_faculty_exports(files, sessions, facts):
    if facts["faculty"].get("publish_names"):
        return files
    names = {s["faculty"] for s in sessions if s["faculty"].lower() not in NO_NAME}
    for n in names:
        for k in files:
            files[k] = files[k].replace(n, "[named in the workbook, not published]")
    return files


def days_json(ctx):
    weeks = []
    for wk in sorted(set(ctx.plan) | set(ctx.capstone)):
        mon = week_monday(ctx, wk)
        kind = ctx.capstone[wk]["kind"] if wk in ctx.capstone else ctx.weeks[wk]["kind"]
        weeks.append({"week": wk, "number": int(wk[1:]), "monday": iso(mon),
                      "saturday": iso(mon + dt.timedelta(days=5)),
                      "span": f"{mon.strftime('%d %b')} to {(mon + dt.timedelta(days=5)).strftime('%d %b %Y')}",
                      "kind": kind, "label": week_label(ctx, wk),
                      "module": ctx.facts["modules"]["weeks"].get(wk),
                      "faculty_sessions": sum(1 for s in ctx.sessions if s["week"] == wk)})
    days = []
    for d in ctx.days:
        days.append({"week": d["week"], "slot": d["slot"], "date": iso(d["date"]),
                     "label": short_date(d["date"]), "weekday": d["weekday"], "kind": d["kind"],
                     "topic": d["topic"], "focus": d["focus"], "module": d["module"],
                     "holiday": d["holiday"],
                     "faculty": [{"id": s["id"], "status": ctx.status_word(s)}
                                 for s in ctx.sessions_on(d["date"])]})
    for wk, c in sorted(ctx.capstone.items()):
        days.append({"week": wk, "slot": "WEEK", "date": iso(c["monday"]),
                     "label": f"{short_date(c['monday'])} to {short_date(c['monday'] + dt.timedelta(days=5))}",
                     "weekday": "Mon", "kind": "capstone", "topic": "Capstone", "focus": c["focus"],
                     "module": ctx.facts["modules"]["weeks"].get(wk), "holiday": None, "faculty": []})
    return json.dumps({"generated_by": "scripts/sync_programme.py", "as_of": str(ctx.facts["as_of"]),
                       "weeks": weeks, "days": days}, indent=1, ensure_ascii=False) + "\n"


def project_pack(ctx, generated):
    """The claude.ai Project's knowledge files: the facts compiled, plus the key exports verbatim."""
    f = ctx.facts
    facts_md = page(
        "Cohort 2 programme facts",
        render_status(ctx, "", "INTERNAL"),
        "\n".join(["## Calendar", "", render_calendar_summary(ctx, "", "INTERNAL"), "",
                   "## Campus day", "", f["campus_day"]["shape"], f["campus_day"]["saturday"], "",
                   "## Cohort", "",
                   f"{f['cohort']['students']['value']} students ({f['cohort']['students']['status']}); "
                   f"{f['cohort']['build_groups']['value']} build-week groups "
                   f"({f['cohort']['build_groups']['status']}); groups of "
                   f"{f['cohort']['group_size']['value']}; {f['cohort']['subproblems_per_build']['value']} "
                   f"sub-problems per build with {f['cohort']['groups_per_subproblem']['value']} groups "
                   f"each ({f['cohort']['groups_per_subproblem']['status']}).", "",
                   "## Modules", "",
                   "; ".join(f"{k} {v}" for k, v in f["modules"]["names"].items()) + ".", "",
                   "## IITGN faculty sessions", "", render_faculty_summary(ctx, "", "INTERNAL"), "",
                   "## Evaluation", "", render_evaluation(ctx, "", "INTERNAL"), "",
                   "## Decisions and conflicts", "", render_decisions(ctx, "", "INTERNAL")]))
    out = {PROJECT_PACK / "01_programme_facts.md": facts_md}
    copies = [("02_calendar.md", PROGRAMME_DOCS / "calendar.md"),
              ("03_20_week_plan.md", pathlib.Path("docs/curriculum/20_Week_Plan.md")),
              ("04_structure.md", pathlib.Path("docs/curriculum/Structure.md")),
              ("05_capstone.md", pathlib.Path("docs/curriculum/W17_20_Capstone.md")),
              ("06_faculty_plan.md", PROGRAMME_DOCS / "faculty-plan.md"),
              ("07_client_zero.md", pathlib.Path("docs/07_Client_Zero.md")),
              ("08_modules_and_credits.md", pathlib.Path("docs/08_Modules_and_Credits.md")),
              ("09_content_doctrine.md", pathlib.Path("docs/02_Content_Doctrine.md")),
              ("10_day_pack_method.md", pathlib.Path("docs/06_Day_Pack_Method.md"))]
    for name, src in copies:
        text = generated.get(src)
        if text is None and src.exists():
            text = src.read_text(encoding="utf-8")
        if text is not None:
            out[PROJECT_PACK / name] = text
    return out


# --------------------------------------------------------------------------- the run
def build(report):
    facts = load_facts()
    generated = {}

    files, summary = ec.export_all(TRACKER)
    for name, text in files.items():
        generated[ec.OUT / name] = text
    wb = openpyxl.load_workbook(TRACKER, data_only=True)
    days, weeks = read_tracker_days(wb, facts, report)
    capstone = read_capstone(wb, facts)
    plan = read_plan(wb)
    sessions, overview, _ = read_faculty(FACULTY, facts, report)
    for k, want in (("Session length (minutes)", facts["faculty"]["session_minutes"]),
                    ("Faculty hours committed", facts["faculty"]["hours_committed"])):
        if k in overview and overview[k] != want:
            report.warn(f"the faculty workbook's input '{k}' is {overview[k]}; facts.yaml says {want}")

    check_calendar(days, plan, capstone, facts, report)
    check_faculty(sessions, days, plan, facts, report)
    ctx = Context(facts, days, weeks, capstone, plan, sessions)

    for name, text in redact_faculty_exports(faculty_exports(FACULTY), sessions, facts).items():
        generated[pathlib.Path("docs/faculty") / name] = text
    jwb = openpyxl.load_workbook(JOURNEY, data_only=True)
    for ws in jwb.worksheets:
        generated[pathlib.Path("docs/journey") / ec.file_name(ws.title)] = "\n".join(ec.export_plain(ws)[0])

    def sat_date(week):
        d = ctx.day.get(f"{week}/SAT")
        return d["date"] if d else None

    papers, notes = bsp.render_all(TRACKER, date_of=sat_date, existing_only=True)
    for path, text in papers.items():
        generated[path.relative_to(ROOT)] = text
    for paper, no, state, why in notes:
        if state == "broken":
            report.error(f"data/programme/paper_edits.yaml {paper} item {no}: {why}")
        elif state == "folded":
            report.warn(f"data/programme/paper_edits.yaml {paper} item {no}: {why}; delete the edit")

    generated[DAYS_JSON] = days_json(ctx)
    generated[PROGRAMME_DOCS / "calendar.md"] = calendar_page(ctx)
    generated[PROGRAMME_DOCS / "faculty-plan.md"] = faculty_page(ctx, report)
    generated[PROGRAMME_DOCS / "decisions.md"] = decisions_page(ctx)

    for path in marker_files():
        text = path.read_text(encoding="utf-8")
        if "<!-- sync:" not in text:
            continue
        new = render_blocks(text, ctx, path, report)
        if new != text:
            generated[path] = new
    generated.update(project_pack(ctx, generated))
    return generated, summary, ctx


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="write nothing; exit 1 if an output is stale or a source disagrees")
    a = ap.parse_args()
    os.chdir(ROOT)

    report = Report()
    generated, summary, ctx = build(report)
    stale = [p for p, text in sorted(generated.items())
             if not p.exists() or p.read_text(encoding="utf-8") != text]
    orphans = sorted(p for p in ec.OUT.glob("*.md") if p.name not in {q.name for q in generated
                                                                    if q.parent == ec.OUT})

    print(f"      {len(ctx.days)} days and {len(ctx.capstone)} capstone weeks read; "
          f"{len(ctx.sessions)} faculty sessions, "
          f"{sum(1 for s in ctx.sessions if ctx.status_word(s) == 'confirmed')} confirmed")
    for w in report.warnings:
        print(f"WARN  {w}")
    for e in report.errors:
        print(f"FAIL  {e}")
    if orphans:
        print("WARN  exports with no tab in the workbook: " + ", ".join(p.name for p in orphans))

    if a.check:
        for p in stale:
            print(f"STALE {p}")
        if report.errors or stale:
            print(f"\n{len(report.errors)} error(s), {len(stale)} stale output(s). "
                  f"Run python3 scripts/sync_programme.py and commit what it writes.")
            sys.exit(1)
        print("      every output is current")
        return

    if report.errors:
        print(f"\n{len(report.errors)} error(s): nothing written. Fix the sources and run again.")
        sys.exit(1)
    for p in stale:
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(generated[p], encoding="utf-8")
        print(f"wrote {p}")
    print(f"      {len(stale)} file(s) updated, {len(generated) - len(stale)} already current")


if __name__ == "__main__":
    main()

# Test inputs and expected outcomes
# --------------------------------
# python3 scripts/sync_programme.py
#     Reads the three workbooks and facts.yaml, prints the day and session counts, and writes the
#     exports, data/programme/days.json, docs/programme/*.md, every sync block and the Project pack.
# python3 scripts/sync_programme.py --check     (straight after the line above)
#     "every output is current", exit 0.
# facts.yaml: faculty.overrides: {W2-2: {date: 2026-10-15}}, then the sync
#     WARN that W2-2 now sits on Thu 15 Oct against the tracker's Tue 13 Oct; the W02/D2 block says
#     the session moved, and the W02/D4 block carries it.
# facts.yaml: faculty.overrides: {W2-2: {date: 2026-10-17}}
#     FAIL: Sat 17 Oct is a saturday day, and a faculty block runs on teaching days only; nothing written.
# facts.yaml: a holiday added on 2026-10-14 with no change to the tracker
#     FAIL: the tracker row for Wed 14 Oct still teaches; nothing written.
# The faculty workbook with a name typed into the Faculty member column, publish_names false
#     FAIL naming the row and the session; nothing written.
# A STUDENT file carrying <!-- sync:evaluation --><!-- /sync:evaluation -->
#     FAIL: the evaluation block never renders in a STUDENT file.
# A STUDENT file with <!-- sync:rubric:W03/mock --><!-- /sync:rubric:W03/mock -->
#     The mock's six criteria render as a table, since Build 1's rubrics are open to learners.
# <!-- sync:rubric:W06 --> in any file while Build 2's rubrics are unsettled
#     FAIL: no settled rubric for W06; it waits for the programme handbook.
# facts.yaml: one Build 1 GD criterion raised from 8 to 9 marks
#     FAIL: the W03 gd criteria add to 31, not 30; nothing written.
# A file with <!-- sync:day-date:W02/D1 -->x<!-- /sync:day-date:W02/D1 -->
#     The x becomes "Mon 12 Oct 2026" on the same line.
